### ISSUE TITLE
Rendered Viewport Shading Does Not Work in Blender 2.8

### ISSUE THREAD

**Issue by happysmash27** [LuxCoreRender/BlendLuxCore#325]
#### System Information

Gentoo Linux, RX 480

#### Software Version

* Blender version: Blender 2.8
* LuxCore version: 2.2

#### Error message from Blender console

```
 ~ % ./Software/blender-2.80rc1-linux-glibc217-x86_64/blender
/var/run/user/1027/gvfs/ non-existent directory
Read prefs: /home/happysmash27/.config/blender/2.80/config/userpref.blend
AL lib: (EE) GetLoadedHrtf: Invalid header in /usr/share/openal/hrtf/default-44100.mhr: "MinPHR02"
AL lib: (EE) GetLoadedHrtf: Failed to load /usr/share/openal/hrtf/default-44100.mhr
AL lib: (EE) GetLoadedHrtf: Invalid header in /usr/share/openal/hrtf/default-48000.mhr: "MinPHR02"
AL lib: (EE) GetLoadedHrtf: Failed to load /usr/share/openal/hrtf/default-48000.mhr
found bundled python: /home/happysmash27/Software/blender-2.80rc1-linux-glibc217-x86_64/2.80/python
BlendLuxCore registered (2.2rc1)
Updating OpenCL device list
==================================================
[Engine/Viewport] New session
[Exporter] Creating session
[SDL][57.566] Camera type: perspective
[SDL][57.566] Camera position: Point[14.7279, -6.50511, 8.01803]
[SDL][57.566] Camera target: Point[13.9091, -6.14344, 7.57226]
[SDL][57.566] Camera clipping plane disabled
ERROR: Error: Object 'Camera' not in View Layer 'View Layer'!

Traceback (most recent call last):
  File "/home/happysmash27/.config/blender/2.80/scripts/addons/BlendLuxCore/engine/viewport.py", line 44, in view_update
    engine.session = engine.exporter.create_session(depsgraph, context, engine=engine)
  File "/home/happysmash27/.config/blender/2.80/scripts/addons/BlendLuxCore/export/__init__.py", line 112, in create_session
    if not self.object_cache2.first_run(self, depsgraph, view_layer, engine, luxcore_scene, scene_props, is_viewport_render):
  File "/home/happysmash27/.config/blender/2.80/scripts/addons/BlendLuxCore/export/caches/object_cache.py", line 56, in first_run
    if not (self._is_visible(dg_obj_instance, obj) or obj.visible_get(view_layer=view_layer)):
RuntimeError: Error: Object 'Camera' not in View Layer 'View Layer'!

new framebuffer
Saved session recovery to '/tmp/quit.blend'

Blender quit
zsh: segmentation fault  ./Software/blender-2.80rc1-linux-glibc217-x86_64/blender
```

#### Short description of error

Rendered viewport shading only results in black silhouettes in Blender 2.8. 

#### Exact steps for others to reproduce the error

Make new blender file, switch to LuxCore, press "Use LuxCore material nodes" on the material for the default cube, then switch to Rendered viewport shading.

**Comment by happysmash27** [comment]
Solution: Upgrade to the newest version of Blender 2.8, rather than its initial release.
