### ISSUE TITLE
cant enable addon, getting errors

### ISSUE THREAD

**Issue by 3diuk** [LuxCoreRender/BlendLuxCore#393]
First, check if your problem was already reported:
https://github.com/LuxCoreRender/BlendLuxCore/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abug

#### System Information

win 10, gtx 1070

#### Software Version

* Blender version: 2.83
* LuxCore version: (2.2
#### Error message from Blender console

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: DLL load failed: The specified module could not be found.

If possible, include a traceback of the error messages.
Paste it into this code block:
```
register_class(...):
Warning: 'text.intelli_menu' doesn't contain '_MT_' with prefix & suffix
addon_utils.disable: BlendLuxCore not disabled
Modules Installed (BlendLuxCore) from 'E:\\blender\\3rd party renderers\\luxcore\\BlendLuxCore-v2.2-blender2.80-win64-opencl.zip' into 'C:\\Users\\3diWorkstation\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons'
Traceback (most recent call last):
  File "E:\blender\dailybuilds\2.83\blender-2.83-dcdcc2348842-windows64\blender-2.83-dcdcc2348842-windows64\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\3diWorkstation\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore\__init__.py", line 23, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception:

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: DLL load failed: The specified module could not be found.
```

#### Short description of error

installed addon, and installed 2 files suggested files for windows (ww_icl_redist_mis and VC_redist.x64.exe)

gtx 1070, i7 7700k, 32 gb ram.

**Comment by 3diuk** [comment]
installing latest studio driver resolved.
