### ISSUE TITLE
Pyside2 setup and python environment under linux

### ISSUE THREAD

**Issue by s-leger** [LuxCoreRender/BlendLuxCore#402]
#### System Information

Operating system Linux

#### Software Version

* Blender version: 2.8x
* LuxCore version: 2.3+ pyluxcoretools.py

#### Short description of error
By default "pyluxcoretools.py" expect a python3 setup and available in PATH.
However blender is bundled with python so why not use this python instance ?
Under linux, in order to use blender's python you should use 
command = [bpy.app.binary_path_python, zip_path]
assuming pyside2 is setup from blender.

There is a blender Pip helper available to setup modules
https://github.com/s-leger/blender-pip/blob/master/README.md

**Comment by CodeFHD** [comment]
Update: As of (Blend)LuxCore v2.10, and it using Blenders new Extensions system, this has again changed.

PySide should be installed via an entry in the `blender_manifest.toml`.

See also https://github.com/LuxCoreRender/BlendLuxCore/issues/1018 as a new, higher-level issue on this topic.

**Comment by howetuft** [comment]
PySide could/should be avoided in this case. For such a simple case, TkInter, bundled with Python, could easily do the job.

**Comment by far-rainbow** [comment]
so this button [LuxCore Network Render] in "LuxCoreTools" bottom menu of Blender's LuxCore menu won't play again on Windows-10:

<img width="381" height="280" alt="Image" src="https://github.com/user-attachments/assets/d1644753-976e-4934-a5e4-58eee712a36b" />

Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.5\4.5\python\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Blender Foundation\Blender 4.5\4.5\python\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] File not found

I've tried Blender 4.5, 4.4, 4.3 and BlendLuxCore 2.10 -- all teh same error
