### ISSUE TITLE
RuntimeError: PathOCLBase kernel compilation error

### ISSUE THREAD

**Issue by flapenguin** [LuxCoreRender/BlendLuxCore#404]
#### System Information

Windows 10 Version 1909 OS Build 18363.720
NVIDIA GeForce GTX 580 (driver 391.35, 03/27/2018, latest one according to GeForce Experience and nvidia website)

#### Software Version

* Blender version: v2.82a
* LuxCore version: 2.3

#### Error message from Blender console

```
[LuxCore][21.157] [PathOCLBaseRenderThread::0] PathOCL kernel compilation error
ERROR clBuildProgram[CL_BUILD_PROGRAM_FAILURE]:
<kernel>:17050:32: error: invalid argument type 'const __global BSDF *' to unary expression
        if (useVisibilityMapCache && (!bsdf || EnvLightVisibilityCache_IsCacheEnabled(bsdf MATERIALS_PARAM))) {
                                      ^~~~~
<kernel>:17147:6: error: invalid argument type 'const __global BSDF *' to unary expression
        if (!bsdf)
            ^~~~~
<kernel>:17183:7: error: invalid argument type 'const __global float *' to unary expression
                if (!infiniteLightDistribution)
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
<kernel>:17291:6: error: invalid argument type 'const __global BSDF *' to unary expression
        if (!bsdf)
            ^~~~~
<kernel>:17322:7: error: invalid argument type 'const __global float *' to unary expression
                if (!skyLightDistribution)
                    ^~~~~~~~~~~~~~~~~~~~~
<kernel>:20914:6: error: invalid argument type 'const __global RadiancePhoton *' to unary expression
        if (!pgicRadiancePhotons)
            ^~~~~~~~~~~~~~~~~~~~

Traceback (most recent call last):
  File "C:\Users\FlaPenguin\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlendLuxCore\engine\base.py", line 84, in render_final
    final.render(self, depsgraph)
  File "C:\Users\FlaPenguin\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlendLuxCore\engine\final.py", line 49, in render
    _render_layer(engine, depsgraph, statistics, layer)
  File "C:\Users\FlaPenguin\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlendLuxCore\engine\final.py", line 73, in _render_layer
    engine.session.Start()
RuntimeError: PathOCLBase kernel compilation error:
ERROR clBuildProgram[CL_BUILD_PROGRAM_FAILURE]:
<kernel>:17050:32: error: invalid argument type 'const __global BSDF *' to unary expression
        if (useVisibilityMapCache && (!bsdf || EnvLightVisibilityCache_IsCacheEnabled(bsdf MATERIALS_PARAM))) {
                                      ^~~~~
<kernel>:17147:6: error: invalid argument type 'const __global BSDF *' to unary expression
        if (!bsdf)
            ^~~~~
<kernel>:17183:7: error: invalid argument type 'const __global float *' to unary expression
                if (!infiniteLightDistribution)
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
<kernel>:17291:6: error: invalid argument type 'const __global BSDF *' to unary expression
        if (!bsdf)
            ^~~~~
<kernel>:17322:7: error: invalid argument type 'const __global float *' to unary expression
                if (!skyLightDistribution)
                    ^~~~~~~~~~~~~~~~~~~~~
<kernel>:20914:6: error: invalid argument type 'const __global RadiancePhoton *' to unary expression
        if (!pgicRadiancePhotons)
            ^~~~~~~~~~~~~~~~~~~~
```

#### Short description of error

Some OpenCL compilation errors. Probably my driver has old version of OpenCL C compiler.

#### Exact steps for others to reproduce the error

Try to render default cube scene with LuxCore OpenCL renderer. LuxCore CPU renderer works ok.

JFYI Cycles is not working on my gpu, because it requires CUDA Compute Capability >= 3.0, and my card has only 2.0.

**Comment by Dade916** [comment]
It is a problem of the version of your OpenCL compilers because the reported errors are clearly valid OpenCL C expressions (and work with recent NVIDIA, AMD and Intel OpenCL drivers).

Does LuxMark work  ?

You could try to install some older driver version, NVIDIA has some time released broken OpenCL drivers in the past. The latest version for your GPU may be one of them. The GTX580 should be able to run Lux so it is about finding a working driver version.

**Comment by flapenguin** [comment]
LuxMark v3.1 works fine, but [v4.0alpha0](https://github.com/LuxCoreRender/LuxMark/releases/tag/luxmark_v4.0alpha0) fails with similar errors:
<details>
<code>
2020-03-22 14:44:02 - [LuxCore] [8.765] [PathOCLBaseRenderThread::0] PathOCL kernel compilation error ERROR clBuildProgram[CL_BUILD_PROGRAM_FAILURE]: :16019:6: error: invalid argument type 'float' to unary expression ((!isTransmitEval && (eventMatA & REFLECT)) || ^~~~~~~~~~~~~~~ :16020:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventMatA & TRANSMIT)))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~ :16043:6: error: invalid argument type 'float' to unary expression ((!isTransmitEval && (eventMatB & REFLECT)) || ^~~~~~~~~~~~~~~ :16044:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventMatB & TRANSMIT)))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~ :16124:7: error: invalid argument type 'float' to unary expression if ((!isTransmitEval && (eventSecond & REFLECT)) || ^~~~~~~~~~~~~~~ :16125:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventSecond & TRANSMIT))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~ :16332:6: error: invalid argument type 'float' to unary expression ((!isTransmitEval && (eventMatA & REFLECT)) || ^~~~~~~~~~~~~~~ :16333:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventMatA & TRANSMIT)))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~ :16356:6: error: invalid argument type 'float' to unary expression ((!isTransmitEval && (eventMatB & REFLECT)) || ^~~~~~~~~~~~~~~ :16357:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventMatB & TRANSMIT)))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~ :16437:7: error: invalid argument type 'float' to unary expression if ((!isTransmitEval && (eventSecond & REFLECT)) || ^~~~~~~~~~~~~~~ :16438:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventSecond & TRANSMIT))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~ :16645:6: error: invalid argument type 'float' to unary expression ((!isTransmitEval && (eventMatA & REFLECT)) || ^~~~~~~~~~~~~~~ :16646:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventMatA & TRANSMIT)))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~ :16669:6: error: invalid argument type 'float' to unary expression ((!isTransmitEval && (eventMatB & REFLECT)) || ^~~~~~~~~~~~~~~ :16670:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventMatB & TRANSMIT)))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~ :16750:7: error: invalid argument type 'float' to unary expression if ((!isTransmitEval && (eventSecond & REFLECT)) || ^~~~~~~~~~~~~~~ :16751:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventSecond & TRANSMIT))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~ :16958:6: error: invalid argument type 'float' to unary expression ((!isTransmitEval && (eventMatA & REFLECT)) || ^~~~~~~~~~~~~~~ :16959:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventMatA & TRANSMIT)))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~ :16982:6: error: invalid argument type 'float' to unary expression ((!isTransmitEval && (eventMatB & REFLECT)) || ^~~~~~~~~~~~~~~ :16983:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventMatB & TRANSMIT)))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~ :17063:7: error: invalid argument type 'float' to unary expression if ((!isTransmitEval && (eventSecond & REFLECT)) || ^~~~~~~~~~~~~~~ :17064:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventSecond & TRANSMIT))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~ :17271:6: error: invalid argument type 'float' to unary expression ((!isTransmitEval && (eventMatA & REFLECT)) || ^~~~~~~~~~~~~~~ :17272:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventMatA & TRANSMIT)))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~ :17295:6: error: invalid argument type 'float' to unary expression ((!isTransmitEval && (eventMatB & REFLECT)) || ^~~~~~~~~~~~~~~ :17296:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventMatB & TRANSMIT)))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~ :17376:7: error: invalid argument type 'float' to unary expression if ((!isTransmitEval && (eventSecond & REFLECT)) || ^~~~~~~~~~~~~~~ :17377:20: error: invalid operands to binary expression ('const __attribute__((address_space(16776963))) float' and 'int') (isTransmitEval && (eventSecond & TRANSMIT))) { ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~ 

2020-03-22 14:44:02 - RUNTIME ERROR: PathOCLBase kernel compilation error
</code>
</details>

I've managed to patch `pyluxcode.pyd` to replace `!x` with `x!=0` (which I agree is a very strange problem) and now render is working. OpenCL for viewport freezes Blender with pixel size 1x, 2x hovewer works fine.
```bash
cp pyluxcore.pyd pyluxcore.pyd.orig
# http://bbe-.sourceforge.net/bbe.html
bbe.exe \
	-e 's/\tif (!bsdf)/if(bsdf!=0)/g' \
	-e 's/ (!bsdf /(bsdf!=0/g' \
	-e 's/\tif (!infiniteLightDistribution)/if(infiniteLightDistribution!=0)/g' \
	-e 's/\tif (!skyLightDistribution)/if(skyLightDistribution!=0)/g' \
	-e 's/\tif (!pgicRadiancePhotons)/if(pgicRadiancePhotons!=0)/g' \
	-o pyluxcore.pyd \
	pyluxcore.pyd.orig
```

**Comment by Dade916** [comment]
Feel free to submit a pull request if you want those changes integrated back on the main sources (however some more  "!NULL" test is likely to sneak in over time because it will be a problem not detected by any developer using a recent driver).
