### ISSUE TITLE
Crash blender with blenderluxcore 2.3 and texture exr

### ISSUE THREAD

**Issue by useranty** [LuxCoreRender/BlendLuxCore#409]
.blend file: 

Steps to reproduce:

simply scene with cube, light, camera material matte and texture exr

Screenshots or rendered images:

Error message from Blender console:

[Engine/Final] Rendering layer "View Layer"
[Exporter] Creating session
[SDL][11.159] Camera type: perspective
[SDL][11.159] Camera position: Point[7.35889, -6.92579, 4.95831]
[SDL][11.159] Camera target: Point[6.70733, -6.31162, 4.51304]
[SDL][11.159] Camera clipping plane disabled
[SDL][11.163] Texture definition: 139809125227832Color
[SDL][11.163] Reading texture map: /home/xxxx/test/blender/../textures/14textures.exr
Writing: /tmp/lux23_test0001.crash.txt
Segmentation fault

OS: Linux Debian 10 64bit, 
Blender version: 2.82a 64bit
LuxCore version: 2.3

blender 2.82a with luxcore 2.2 and exr work without crash

**Comment by Theverat** [comment]
Can you please upload a small .blend file with packed texture?

**Comment by useranty** [comment]
[lux23_test0001.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4387953/lux23_test0001.blend.zip)

**Comment by Theverat** [comment]
I can reproduce it on Ubuntu 19.10.

gdb backtrace: 
```
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x00007fffbd87d1ea in Imf_2_2::Header::~Header() ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#2  0x00007fffbd885908 in Imf_2_2::InputFile::Data::~Data() ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#3  0x00007fffbd88595e in Imf_2_2::InputFile::Data::~Data() ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#4  0x00007fffbd883deb in Imf_2_2::InputFile::~InputFile() ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#5  0x00007fffbd883e1e in Imf_2_2::InputFile::~InputFile() ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#6  0x00007fffbd8c740f in Imf_2_2::MultiPartInputFile::~MultiPartInputFile() ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#7  0x00007fffbd8c75ce in Imf_2_2::MultiPartInputFile::~MultiPartInputFile() ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#8  0x00007fffbd27ff56 in OpenImageIO_v1_8::OpenEXRInput::close() ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#9  0x00007fffbc77d1c2 in slg::ImageMap::ImageMap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, slg::ImageMapStorage::StorageType, slg::ImageMapStorage::WrapType) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#10 0x00007fffbc7a2b81 in slg::ImageMapCache::GetImageMap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, slg::ImageMapStorage::ChannelSelectionType, slg::ImageMapStorage::StorageType, slg::ImageMapStorage::WrapType) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#11 0x00007fffbc7d6c3f in slg::Scene::CreateTexture(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, luxrays::Properties const&) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#12 0x00007fffbc7e1e28 in slg::Scene::ParseTextures(luxrays::Properties const&) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#13 0x00007fffbc7eaf26 in slg::Scene::Parse(luxrays::Properties const&) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#14 0x00007fffbc6300ff in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (luxcore::detail::SceneImpl::*)(luxrays::Properties const&), boost::python::default_call_policies, boost::mpl::vector3<void, luxcore::detail::SceneImpl&, luxrays::Properties const&> > >::operator()(_object*, _object*) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#15 0x00007fffbd98009d in boost::python::objects::function::call(_object*, _object*) const ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#16 0x00007fffbd9801f8 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#17 0x00007fffbd9875b3 in boost::python::handle_exception_impl(boost::function0<void>) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#18 0x00007fffbd97da09 in function_call ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#19 0x0000000005d48c44 in _PyObject_FastCallKeywords ()
#20 0x0000000001652612 in _PyEval_EvalFrameDefault ()
#21 0x0000000005dfa4bc in _PyEval_EvalCodeWithName ()
#22 0x0000000005d485a6 in _PyFunction_FastCallKeywords ()
#23 0x00000000016538f2 in _PyEval_EvalFrameDefault ()
#24 0x0000000005dfa4bc in _PyEval_EvalCodeWithName ()
#25 0x0000000005d485a6 in _PyFunction_FastCallKeywords ()
#26 0x00000000016540ac in _PyEval_EvalFrameDefault ()
#27 0x000000000164a720 in  ()
#28 0x0000000005d484e6 in _PyFunction_FastCallDict ()
#29 0x0000000001b47dae in  ()
#30 0x0000000001ada467 in  ()
#31 0x00000000019801c1 in  ()
#32 0x00000000019543e1 in  ()
--Type <RET> for more, q to quit, c to continue without paging--
#33 0x0000000001955798 in DRW_draw_render_loop_ex ()
#34 0x0000000001f2d3b7 in view3d_main_region_draw ()
#35 0x0000000001b6ae91 in ED_region_do_draw ()
#36 0x000000000181e1a6 in wm_draw_update ()
#37 0x000000000181c210 in WM_main ()
#38 0x000000000159ea77 in main ()
```
