### ISSUE TITLE
blender:v2.9 error while loading pyluxcore

### ISSUE THREAD

**Issue by bartoszek** [LuxCoreRender/BlendLuxCore#496]
Error message from Blender console:
```
Traceback (most recent call last):
  File "/usr/share/blender/2.90/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/2.90/scripts/addons/luxcorerender/__init__.py", line 50, in <module>
    import pyluxcore
SystemError: initialization of pyluxcore raised unreported exception
```
sys.env {Linux:Arch, gcc:10.1.0, python:3.8}
Blender version: Blender 2.90.0 Alpha, build date: 2020-06-29, build hash: b29fd7bab80b
LuxCore version: 2.4.beta1.r1.g35eca7c19

**Comment by Theverat** [comment]
Blender 2.90 is not supported by BlendLuxCore (as all under-development Blender versions).
