### ISSUE TITLE
OpenCL driver API error (code: -1001)

### ISSUE THREAD

**Issue by dadaromeo** [LuxCoreRender/BlendLuxCore#529]
.blend file: 

Steps to reproduce:

Screenshots or rendered images:
![Screenshot_2020-07-30_14-12-51](https://user-images.githubusercontent.com/5675732/88927102-da5d3b00-d26e-11ea-8a29-2bea8591a115.png)

Error message from Blender console: Traceback (most recent call last):
  File "/home/romeo/.config/blender/2.83/scripts/addons/BlendLuxCore/handlers/load_post.py", line 59, in handler
    updated = scene.luxcore.devices.update_devices_if_necessary()
  File "/home/romeo/.config/blender/2.83/scripts/addons/BlendLuxCore/properties/devices.py", line 41, in update_devices_if_necessary
    device_props = self.get_device_props()
  File "/home/romeo/.config/blender/2.83/scripts/addons/BlendLuxCore/properties/devices.py", line 99, in get_device_props
    return pyluxcore.GetOpenCLDeviceDescs()
RuntimeError: OpenCL driver API error (code: -1001, file:/home/vsts/work/1/s/LinuxCompile/LuxCore/src/luxrays/devices/ocldevice.cpp, line: 72): -1001

OS: UbuntuStudio 20.04
Blender version: 2.83
LuxCore version: 2.4

**Comment by Dade916** [comment]
Error "-1001" means OpenCL is not available on your platform. You should fix OpenCL support by installing appropriate drivers from AMD or NVIDIA.

Try to run LuxMark to check if your OpenCL installation is working. "clinfo" command can help too.

**Comment by dadaromeo** [comment]
> Error "-1001" means OpenCL is not available on your platform. You should fix OpenCL support by installing appropriate drivers from AMD or NVIDIA.
> 
> Try to run LuxMark to check if your OpenCL installation is working. "clinfo" command can help too.

I'm on Intel i3 and I use the 'ocl-icd-libopencl1' ICD loader driver. When I uninstall the 'ocl-icd-libopencl1', BlenderLuxCore works fine but I have to install it via snap because the removal of 'ocl-icd-libopencl1' also removes the blender package along side a bunch of other packages like ffmpeg, gimp, vlc, ... and a lot more, about ~1.5 GB of packages that depend on it.

But when the 'ocl-icd-libopencl1' is installed, even the blender installed via snap shows the same message.

**Comment by Dade916** [comment]
I'm starting to understand the problem: LuxCore detects OpenCL but than no available platform is found (and this is quit a uncommon case).

As simple workaround, you could install Intel OpenCL **CPU** driver (note: CPU, not GPU). It will add an OpenCL CPU device to your installation, it will still useless for rendering but it will workaround this problem.

In the mean time, I can fix this situation in the under development v2.5.

**Comment by dadaromeo** [comment]
I installed the 'pocl-opencl-icd' package and the issue is solved. @Dade916 thank you for your guidelines.
