### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by anindya-jana** [LuxCoreRender/BlendLuxCore#531]
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\piku\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore\__init__.py", line 35, in <module>
    AddDllDirectory = windll.kernel32.AddDllDirectory
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\ctypes\__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\ctypes\__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'AddDllDirectory' not found
```

**Comment by Theverat** [comment]
What OS do you have?

**Comment by Theverat** [comment]
Apparently, on Windows 7, you need to install this update:
https://www.microsoft.com/en-us/download/details.aspx?id=26764

**Comment by anindya-jana** [comment]
Ok i should upgrade
