### ISSUE TITLE
LOL shows no previews

### ISSUE THREAD

**Issue by MarioPeper** [LuxCoreRender/BlendLuxCore#560]
Sometimes LOL shows no thumbnails, sometimes only the first row, sometimes also the 2nd, but then it stops and doesn't load further. Are these server problems. I usually have a good internet connection. I wonder if anyone else has?

**Comment by foreachthing** [comment]
I never got that working either, so I downloaded (cloned) the repo https://github.com/LuxCoreRender/LoL and extracted everything manually. Not very elegant but it's working now.

**Comment by MarioPeper** [comment]
Ahh... Thanks for the hint. But apparently it works for everyone else. A little weird?!

**Comment by Theverat** [comment]
Are there any error messages in the console?

**Comment by MarioPeper** [comment]
yes I attach it as .txt. Looks like it can not write and then it hangs in a loop.
[LOL_error.txt](https://github.com/LuxCoreRender/BlendLuxCore/files/5168180/LOL_error.txt)

**Comment by MarioPeper** [comment]
Okey thanks, but blenderkit works fine. However, I remember that there was something like that. But it was a bit ago.

**Comment by foreachthing** [comment]
Ok!!! Newest Version of everything seems to work! :+1:
Blender 2.83.5 and latest BlendLuxCore does download models and material. Thumbnails are being created.

**Comment by MarioPeper** [comment]
Unfortunately not for me. It seems that something has changed during loading. The preview pictures of the first two rows are already downloaded. I don't know what LOL downloads but this is my network history after the start of LOL.
![network history](https://user-images.githubusercontent.com/66747679/92120354-392b4c80-edf9-11ea-913c-7558c98fa5dc.png)

**Comment by MarioPeper** [comment]
No changes with the last update. Am I really the only one who has this problem?
![LOL_a](https://user-images.githubusercontent.com/66747679/93784928-d1b13180-fc2d-11ea-9675-e23a50c7b06f.png)
![LOL_b](https://user-images.githubusercontent.com/66747679/93784939-d4ac2200-fc2d-11ea-9719-6131a98ada49.png)

**Comment by neo2068** [comment]
Can you check the console output of the blender addon? Are there any error messages? I have an idea what could be the problem but it need some time to implement the fix. Did  you try to download the github repository of the online library ([](https://github.com/LuxCoreRender/LoL)) and place the model and material files inside the LuxCoreOnlineLibrary_data?

**Comment by MarioPeper** [comment]
Yes I attach it as .txt. but looks like the same i put in the post to @Theverat. And i download the repository like @foreachthing suggest me. 
[LOL_22_09_20.txt](https://github.com/LuxCoreRender/BlendLuxCore/files/5262173/LOL_22_09_20.txt)
These are the errors after activating the LOL Asset bar.

**Comment by neo2068** [comment]
If you have the thumbnails on your PC, it will not load them from the server. There have to be another problem then. It seems you are on Linux? Where do you store the LoL files you downloaded from the repository?

**Comment by MarioPeper** [comment]
Yes I am on Linux, they are in: /home/pepi/LuxCoreOnlineLibrary_data/ I thought this is the default folder?

**Comment by neo2068** [comment]
It is the default folder and should be correct. I have pushed a fix for manually placing the preview files in the preview directory. Can you test if it works for you with the latest BlendLuxCore?

**Comment by MarioPeper** [comment]
Yes thanks, now the small previews for the models work. But not the big ones. If I click on one of them nothing happens (it stops at 0% download). The material previews do not work yet. Maybe I did not use the right folders. The exact hierarchy would be interesting.
I wonder if it has something to do with write rights of Linux. But i don't think i am the only one here who uses luxcore with linux. But now I know from which file I can append something, so thank you. I'm sure that all this didn't work under 2.4 ,first. And then it did in the final version. Und wie ich schon sagte, mit BlenderKit funktioniert alles, so when this is based of it ?!?

**Comment by neo2068** [comment]
Hi! The preview image handling is one thing which were changed after adapting the blenderkit addon because of the big memory consumption. The folder structure is like the following.

LuxCoreOnlineLibrary_data
   |--model                              => model asset .blend files
   |      |--local                          => local model asset .blend files
   |      |--preview                     => low res (!28x128) preview images
   |               |--full                   => full size preview images, (e.g. 1080x1080)
   |                     |--local           => full size preview images for local files
   |               |--local                 => low res (!28x128) preview images for local files  
   |--material
           |-- same structure as in model

It is strange that the big preview images are not available. But as you said perhaps it is some problem with write permission in the 'full' folder.

**Comment by MarioPeper** [comment]
Thanks, i don't have the small previews for the material and also have a "scene" folder below "LuxCoreOnlineLibrary_data" which contains "preview" and "full" but without content.
Maybe it makes sense to delete the whole "LuxCoreOnlineLibrary_data" and install Blendluxcore again. Because if it would be a write permission problem, other Linux people would have it too.

**Comment by neo2068** [comment]
There are only the full preview files on the server and the small previews are generated on the fly. With the latest version it should be possible to copy the full res thumbnails in the 'preview' folder as in the github repository and the addon will copy it to the 'full' folder and save a downscaled version in the 'preview' folder. This step is not working on your side. Can you check if the files in the 'preview' folder has full resolution or 128x128 pixels? The folder are generated by the addon, too. Therefor the access rights for the folders should be sufficient. Did you use the latest BlendLuxCore version from here [https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.4](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.4) ?

**Comment by MarioPeper** [comment]
No, I'm using the latest version 2.5. Since I fixed the hierarchy something seems to have changed.
It loads the small thumbnails for models from disk but for material from the net (but at every start). Almost all (but only almost) :-).  The big ones are not showing of (but are there). The cpu is very busy working in material view. And the download only works up to 99% for material, then it hangs or crashes. But the file is in the folder and works. So way better now, thank you.

**Comment by neo2068** [comment]
Yes, I meant the latest 2.5 release. I linked the wrong version. I have to investigate why it behaves different on material assets. It uses the same code internally.

**Comment by MarioPeper** [comment]
I do not understand why nobody else has this problem. 
Well, it works like this after starting blender: no net traffic, no cpu action. After activating asset bar, download for about 20-30 seconds and a 20%-30% cpu usage. After activation of material button: 1 cpu core 100% the rest 10%-20%, takes about 2-3 minutes. And at the same time another 20-30 seconds download as described above. The last 2 rows of thumbnails of material are not loaded. With model 2 rows of thumbnails are not in the middle. The big ones are not displayed even if they are in the right folder. Hope the description helps so far. But thanks so I can at least do something with LOL.

**Comment by joc11** [comment]
> I do not understand why nobody else has this problem.

Well I do on OpenSuse :). LOL is downloading and overwriting the preview and full size images, whenever I activate the asset bar in a new .blend file. The thumbnails show up, the large previews not.

**Comment by neo2068** [comment]
@joc11 Can you post the console output? Are there any error messages?

**Comment by joc11** [comment]
> @joc11 Can you post the console output? Are there any error messages?
Some at the end, yes.
`Read prefs: /home/joc/.config/blender/2.92/config/userpref.blend
register_class(...):
Warning: 'an_SocketUiList_Normal' does not contain '_UL_' with prefix and suffix
register_class(...):
Warning: 'an_data_input_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'an_developer_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'an_templates_menu_in_header' does not contain '_HT_' with prefix and suffix
register_class(...):
Warning: 'an.context_pie' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_rotation_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_matrix_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_text_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_boolean_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_overview_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'an_tree_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'an_object_utils_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_mesh_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_list_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_mesh_generators_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_mesh_operators_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_create_list_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_mesh_finalizing_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_create_list_menu_extended' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_combine_list_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_spline_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_animation_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_id_keys_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'an_interpolation_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_color_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_falloff_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_problems_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'an_material_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_number_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_particle_system_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_node_settings_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'an_sound_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_subprograms_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_combine_list_menu_extended' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_SpectrumItemsUiList' does not contain '_UL_' with prefix and suffix
register_class(...):
Warning: 'an_sequence_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an.selection_pie' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_fcurve_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_geometry_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_vector_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_AverageItemsUiList' does not contain '_UL_' with prefix and suffix
register_class(...):
Warning: 'an_kdtree_bvhtree_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_viewer_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_auto_execution_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'an_layout_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'an_object_menu' does not contain '_MT_' with prefix and suffix
Registered Animation Nodes
BlendLuxCore 2.5beta1 registered (with pyluxcore 2.5beta1)
Updating device list
Traceback (most recent call last):
  File "/home/joc/.config/blender/2.92/scripts/addons/BlendLuxCore/handlers/lol/timer.py", line 72, in timer_update
    thread.start()
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/threading.py", line 848, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
Exception in thread Thread-169:
Traceback (most recent call last):
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/joc/.config/blender/2.92/scripts/addons/BlendLuxCore/utils/lol/utils.py", line 377, in run
    file_handle.write(url_handle.read())
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/http/client.py", line 470, in read
    s = self._safe_read(self.length)
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/http/client.py", line 620, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

Exception in thread Thread-334:
Traceback (most recent call last):
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/joc/.config/blender/2.92/scripts/addons/BlendLuxCore/utils/lol/utils.py", line 377, in run
    file_handle.write(url_handle.read())
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/http/client.py", line 470, in read
    s = self._safe_read(self.length)
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/http/client.py", line 620, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

Exception in thread Thread-376:
Traceback (most recent call last):
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/joc/.config/blender/2.92/scripts/addons/BlendLuxCore/utils/lol/utils.py", line 377, in run
    file_handle.write(url_handle.read())
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/http/client.py", line 470, in read
    s = self._safe_read(self.length)
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/http/client.py", line 620, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/home/joc/Programme/blender-git/build_linux/bin/2.92/python/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
`

**Comment by MarioPeper** [comment]
@joc11 good to see that someone else has this problem. Maybe this will help the developers to find out what it is all about. To me, your error messages look exactly like mine.

**Comment by joc11** [comment]
Fixed for me with latest dayly build on blender 3.0.

**Comment by inegvin** [comment]
Having the same issue. "Thumbnail not ready" for any file from the library. No errors were shown. I still can download assets, I just can't see what am I downloading. Blender 3.0, the latest build downloaded today  (07.02.2022)

**Comment by neo2068** [comment]
@inegvin Can you give more information? What OS do you use? Are there any messages on the Blender console? What is the content of the LuxCore Online Library Directory. You can find the path in the preferences menu under global files directory.

**Comment by CodeFHD** [comment]
I have checked this again, there are indeed a few previews missing.
I noticed a few months ago that there were some issues in the ToC with wrong file names, missing data etc.

It will be adressed during v2.11 development, an update to LoL after the webshosting move has been pending for too long anyways...

I assume the network spike at the next opening is some attempt to re-download those files.

**Comment by CodeFHD** [comment]
Closing this Issue for cleanup purposes.

The issue with file-hosting still exists, but it is not an Issue of BlendLuxCore itself and will hence be tracked outside this Issue tracker.
