### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by vacs-hoantt** [LuxCoreRender/BlendLuxCore#602]
Traceback (most recent call last):
  File "E:\xxx\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\D066\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendLuxCore-master\__init__.py", line 63, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: cannot import name 'pyluxcore' from 'BlendLuxCore-master.bin' (C:\Users\D066\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendLuxCore-master\bin\__init__.py)

**Comment by Theverat** [comment]
It sounds like you downloaded just the repository instead of one of the packaged releases.
