### ISSUE TITLE
(BlendLuxCore 2.4) RuntimeError: CUDA driver API error CUDA_ERROR_NO_DEVICE ... no CUDA-capable device is detected

### ISSUE THREAD

**Issue by thima2017** [LuxCoreRender/BlendLuxCore#604]
The full message:
```
Traceback (most recent call last):
  File "/opt/blender/blender-2.83.9-linux64/2.83/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/home/user/.config/blender/2.83/scripts/addons/BlendLuxCore/__init__.py", line 93, in register
    pyluxcore.Init(LuxCoreLog.add)
RuntimeError: CUDA driver API error CUDA_ERROR_NO_DEVICE (code: 100, file:/home/vsts/work/1/s/LinuxCompile/LuxCore/src/luxrays/core/init.cpp, line: 65): no CUDA-capable device is detected
```
This message appears when I try to enable the addon. I don't have CUDA device installed indeed, only a drivers, but that wasn't a problem with BlendLuxCore 2.2. Now this error prevents the addon activation. I tried the current latest build too with the same result. All of that was happening on blender 2.83.
That message is the message of the first attempt of activation. The second and further messages are:
```
Traceback (most recent call last):
  File "/opt/blender/blender-2.83.9-linux64/2.83/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/home/user/.config/blender/2.83/scripts/addons/BlendLuxCore/__init__.py", line 86, in register
    nodes.materials.register()
  File "/home/user/.config/blender/2.83/scripts/addons/BlendLuxCore/nodes/materials/__init__.py", line 5, in register
    nodeitems_utils.register_node_categories("LUXCORE_MATERIAL_TREE", luxcore_node_categories_material)
  File "/opt/blender/blender-2.83.9-linux64/2.83/scripts/modules/nodeitems_utils.py", line 105, in register_node_categories
    raise KeyError("Node categories list '%s' already registered" % identifier)
KeyError: "Node categories list 'LUXCORE_MATERIAL_TREE' already registered"

```

**Comment by thima2017** [comment]
[BlendLuxCore 2.3 opencl](https://github.com/LuxCoreRender/BlendLuxCore/releases/download/blendluxcore_v2.3/BlendLuxCore-v2.3-linux64-opencl.zip) does work for me.

**Comment by Dade916** [comment]
It is bit a corner case, I have modified the under development v2.5 sources to handle this case too. You can install an automatic build when it is ready (in a couple of hours) from https://forums.luxcorerender.org/viewtopic.php?f=9&t=2805 to check if they works.

Note: v2.3 doesn't have CUDA support at all.

**Comment by thima2017** [comment]
I've tried latest build from https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-linux64.zip and it works. Thank you for the fast fix and for everything else!

**Comment by thima2017** [comment]
The only program I can show lasers and rainbows...
