### ISSUE TITLE
Luxcore not showing up

### ISSUE THREAD

**Issue by gregochan** [LuxCoreRender/BlendLuxCore#666]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_2.92.100.0_x64__ppwjx1n5r4v9t\Blender\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\GregoryC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlendLuxCore\__init__.py", line 79, in <module>
    auto_load.init()
  File "C:\Users\GregoryC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlendLuxCore\auto_load.py", line 26, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\GregoryC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlendLuxCore\auto_load.py", line 54, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\GregoryC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlendLuxCore\auto_load.py", line 58, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_2.92.100.0_x64__ppwjx1n5r4v9t\Blender\2.92\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\GregoryC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlendLuxCore\ui\scene_lightgroups.py", line 3, in <module>
    from ..properties.lightgroups import MAX_CUSTOM_LIGHTGROUPS
ImportError: cannot import name 'MAX_CUSTOM_LIGHTGROUPS' from 'BlendLuxCore.properties.lightgroups' (C:\Users\GregoryC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlendLuxCore\properties\lightgroups.py)

**Comment by CodeFHD** [comment]
Closing this issue after a review with the following reasons/conclusions:
- Issue affected old Blender + LuxCore versions that are no longer supported
- Issue was likely individual broken installation (common issue)

If you feel this issue is still relevant in 2025, please re-test it with a recent Blender + LuxCore version, then ask to reopen and provide the following information:
- Operating System
- CPU + GPU model
- Blender and LuxCoreRender version used for re-test
- Detailed steps how to reproduce the bug from an empty scene,
- provide a specific .blend-file
