### ISSUE TITLE
ERROR: Python int too large to convert to C long

### ISSUE THREAD

**Issue by foreachthing** [LuxCoreRender/BlendLuxCore#674]
Steps to reproduce:
Viewport or full render -> `ERROR: Python int too large to convert to C long`
It won't render anything anymore. Every file (even "new") is affected.

Error message from Blender console:

```
[Engine/Viewport] New session
[Exporter] Creating session
[SDL][6.312] Define ImageMap: NamedObject
[SDL][6.312] Camera type: perspective
[SDL][6.312] Camera position: Point[-1.2093, 0.537765, 0.135]
[SDL][6.312] Camera target: Point[-1.2143, -0.462222, 0.135]
[SDL][6.312] Camera clipping plane disabled
ERROR: Python int too large to convert to C long
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlendLuxCore\engine\viewport.py", line 76, in view_update
    engine.session = engine.exporter.create_session(depsgraph, context, engine=engine)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlendLuxCore\export\__init__.py", line 110, in create_session
    scene_props, context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlendLuxCore\export\caches\object_cache.py", line 296, in first_run
    scene_props, is_viewport_render, view_layer, engine)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlendLuxCore\export\caches\object_cache.py", line 367, in _convert_obj
    props = exported_stuff.get_props()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlendLuxCore\export\caches\exported_data.py", line 46, in get_props
    return utils.create_props(prefix, definitions)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlendLuxCore\utils\__init__.py", line 124, in create_props
    props.Set(pyluxcore.Property(prefix + k, v))
OverflowError: Python int too large to convert to C long
```

If you need more info, please let me know.

OS: Win10 20H2
Blender version: 2.92.0
LuxCore version: 2.6a0
Downloaded from https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-win64.zip

**Comment by Dade916** [comment]
It is under investigation here: https://forums.luxcorerender.org/viewtopic.php?f=9&t=736&start=100#p29875

**Comment by Dade916** [comment]
Fixed.

**Comment by foreachthing** [comment]
Thanks! It works as expected!
