### ISSUE TITLE
PathOCL kernel OpenCL program compilation error

### ISSUE THREAD

**Issue by mon64** [LuxCoreRender/BlendLuxCore#697]
Description:
OpenCL kernel compilation fails after approx. 30 minutes with PathOCL kernel OpenCL program compilation error.

.blend file:
Not needed, problem happens even in Blender default startup scene.

Steps to reproduce:
In Blender initiate viewport render or F12 render using GPU.

Error message from Blender console:
[LuxRays][1726.047] [PathOCL kernel] OpenCL program compilation error
ERROR -11[CL_BUILD_PROGRAM_FAILURE]:
Error compiling program for AdvancePaths_MK_RT_NEXT_VERTEX.
Frontend phase failed compilation.
Error: Creating kernel AdvancePaths_MK_RT_NEXT_VERTEX failed!
ERROR: PathOCL kernel OpenCL program compilation error
Traceback (most recent call last):
  File "C:\Users\Lukas\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendLuxCore\engine\viewport.py", line 76, in view_update
    engine.session = engine.exporter.create_session(depsgraph, context, engine=engine)
  File "C:\Users\Lukas\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendLuxCore\export\__init__.py", line 216, in create_session
    pyluxcore.KernelCacheFill(config_props_copy)
RuntimeError: PathOCL kernel OpenCL program compilation error

Entire Blender console content:
[blender_console.txt](https://github.com/LuxCoreRender/BlendLuxCore/files/6645450/blender_console.txt)

OS: Windows 10 Pro (version 1909)
Blender version: 2.93.0 (official release build)
LuxCore version: 2.6 (alpha0 build, commit 9a86b61f3732cd9063655fb3a733ab76ce9c0ec4)

Hardware:
CPU: AMD A8-4500M (with Radeon HD 7640G)
GPU: AMD Radeon HD 7670M
RAM: 16 GB (+ 16 GB page file)

**Comment by CodeFHD** [comment]
Closing this issue after a review with the following reasons/conclusions:
- Issue affected old Blender + LuxCore versions that are no longer supported
- Issue is likely AMD driver related (common issue) and hence could not / would not be fixed in LuxCore at the present time

If you feel this issue is still relevant in 2025, please re-test it with a recent Blender + LuxCore version, then ask to reopen and provide the following information:
- Operating System
- CPU + GPU model
- Blender and LuxCoreRender version used for re-test
- Detailed steps how to reproduce the bug from an empty scene,
- provide a specific .blend-file
