### ISSUE TITLE
Can't install Luxcore on Blender

### ISSUE THREAD

**Issue by AsrielDewitt** [LuxCoreRender/BlendLuxCore#720]
Error message from Blender console:Traceback (most recent call last):
  File "C:\Users\Hafiz\Desktop\Source Test\blender-3.0.0-alpha+cycles-x.bbd0dcec4c64-windows.amd64-release\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Hafiz\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlendLuxCore\__init__.py", line 63, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: DLL load failed while importing pyluxcore: The specified module could not be found.

OS: Windows 10
Blender version: 2.93
LuxCore version:2.5

And yes, I did installed all the required redist. Still got the issue

**Comment by juangea** [comment]
For 2.93 you need LuxCore 2.6, mainly because the Python version got upgraded to 3.9

**Comment by CodeFHD** [comment]
Closing this issue after a review with the following reasons/conclusions:
- Issue affected old Blender + LuxCore versions that are no longer supported
- Issue was answered, no follow-up in 3 years

If you feel this issue is still relevant in 2025, please re-test it with a recent Blender + LuxCore version, then ask to reopen and provide the following information:
- Operating System
- CPU + GPU model
- Blender and LuxCoreRender version used for re-test
- Detailed steps how to reproduce the bug from an empty scene,
- provide a specific .blend-file
