### ISSUE TITLE
TypeError on 3.01 with Master

### ISSUE THREAD

**Issue by JoelGodin** [LuxCoreRender/BlendLuxCore#750]
Mac Blender 3.01 , lux core master:
Cannot install:

Traceback (most recent call last):
  File "/Applications/Blender/Blender3.1ARM1118.app/Contents/Resources/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/joelgodin/Library/Application Support/Blender/3.1/scripts/addons/BlendLuxCore-master/__init__.py", line 47, in <module>
    if not os.access(denoiser_path, os.X_OK):
TypeError: access: path should be string, bytes or os.PathLike, not NoneType

**Comment by dimitre** [comment]
+1 for this issue

**Comment by CodeFHD** [comment]
Closing this issue after a review with the following reasons/conclusions:
- Issue affected old Blender + LuxCore versions that are no longer supported
- Issue was likely individual broken installation (common issue)

If you feel this issue is still relevant in 2025, please re-test it with a recent Blender + LuxCore version, then ask to reopen and provide the following information:
- Operating System
- CPU + GPU model
- Blender and LuxCoreRender version used for re-test
- Detailed steps how to reproduce the bug from an empty scene,
- provide a specific .blend-file

**Comment by dimitre** [comment]
Beautiful. I'm already testing latest prerelease in Blender 4.32
