### ISSUE TITLE
Missing pyluxcore for 2.93.8LTS and BlendLuxCore 2.6 (have 'x86_64', need 'arm64e')

### ISSUE THREAD

**Issue by JoelGodin** [LuxCoreRender/BlendLuxCore#751]
.blend file: 

Steps to reproduce: Enable addon

Error message from Blender console:
Traceback (most recent call last):
  File "/Applications/Blender/Blender 2.93.8LTSarm.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/joelgodin/Library/Application Support/Blender/2.93/scripts/addons/BlendLuxCore/__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: dlopen(/Users/joelgodin/Library/Application Support/Blender/2.93/scripts/addons/BlendLuxCore/bin/pyluxcore.so, 0x0002): tried: '/Users/joelgodin/Library/Application Support/Blender/2.93/scripts/addons/BlendLuxCore/bin/pyluxcore.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/pyluxcore.so' (no such file)

OS: Apple M1 macOS
Blender version: 2.93.8 LTS (Apple Silicon)
LuxCore version: BlendLuxCore v2.6

**Comment by JoelGodin** [comment]
It works if I download 2.93.8 LTS Intel and run 2.6 luxcore but ARM throws an error.

**Comment by dimitre** [comment]
Same thing here. Did it work for you @JoelGodin  using Intel version? or some previous version?

**Comment by u3dreal** [comment]
There currently is not arm64 version since i do not have access to an M1 machine.

**Comment by electricgobo** [comment]
Yet, is there a M1/A-Silicon-Version planned?

**Comment by lcombaldieu** [comment]
I have the same issue on my mac :
![image](https://user-images.githubusercontent.com/28562040/169252673-9cd4d924-bc45-429f-8c82-dff847a16ed1.png)

**Comment by dimitre** [comment]
@u3dreal I can make one M1 machine available remotely if it helps. I have one spare here those days
