### ISSUE TITLE
Can't install on 3.0.1 on linux.

### ISSUE THREAD

**Issue by asluizh** [LuxCoreRender/BlendLuxCore#753]
Was able to install on 3.0.0
After updating blender and upon opening the program, luxcore addon was disabled. Trying to re-enable it produced an error. Removing it and installing it again gave the same error.

Error message from Blender console:

```
Traceback (most recent call last):
  File "/usr/share/blender/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user/.config/blender/3.0/scripts/addons/BlendLuxCore/__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: /home/user/.config/blender/3.0/scripts/addons/BlendLuxCore/bin/pyluxcore.so: undefined symbol: _PyTraceMalloc_NewReference
```

OS: Manjaro Linux 
Blender version: 3.0.1
LuxCore version: Latest build (d435660, 8 jan 2022)

**Comment by SteffenDuenner** [comment]
Hmm... I can activate it in (Linux) Blender 3.0.1 and it works (except for the bug I already reported https://github.com/LuxCoreRender/BlendLuxCore/issues/745 ).

But I get a similar error message as you got when I try to activate it in Blender 3.1.0.

**Comment by edin45** [comment]
Same here, with Blender 3.1.0

**Comment by neo2068** [comment]
Blender 3.1 uses Python 3.10 dependencies. The latest version of LuxCore uses 3.9 to be compatible with Blender 3.0. LuxCore has to be built with the same Python version as Blender.

**Comment by neo2068** [comment]
The latest version should work with Blender 3.1 now. [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest)
Please check and comment if it works for you.

**Comment by SteffenDuenner** [comment]
The Python updates that were committed are Windows-only sadly. So no change for Linux users yet.

**Comment by asluizh** [comment]
Indeed, the error persists on 3.1 with the latest build (march 14) on linux.

`Traceback (most recent call last):
  File "/usr/share/blender/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user/.config/blender/3.1/scripts/addons/BlendLuxCore/__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: /home/user/.config/blender/3.1/scripts/addons/BlendLuxCore/bin/pyluxcore.so: undefined symbol: _PyTraceMalloc_NewReference

`

**Comment by CodeFHD** [comment]
Closing this issue after a review with the following reasons/conclusions:
- Issue affected old Blender + LuxCore versions that are no longer supported
- Based on answers given, issue is obsolete by now

If you feel this issue is still relevant in 2025, please re-test it with a recent Blender + LuxCore version, then ask to reopen and provide the following information:
- Operating System
- CPU + GPU model
- Blender and LuxCoreRender version used for re-test
- Detailed steps how to reproduce the bug from an empty scene,
- provide a specific .blend-file
