### ISSUE TITLE
blendluxcore isn't working in 3.1

### ISSUE THREAD

**Issue by SlincHD** [LuxCoreRender/BlendLuxCore#754]
the blend luxcore addon dosn't work in blender 3.1 also there is no error i just can't enable the addon in the prefrences.

using blender 3.1 and the lates blendluxcore build

**Comment by SlincHD** [comment]
so with the lates build i was trying to enable it and this time it gave me an error: 
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlendLuxCore\__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: DLL load failed while importing pyluxcore: Das angegebene Modul wurde nicht gefunden.

i hope that is helpfull

**Comment by neo2068** [comment]
Blender 3.1 uses Python 3.10 dependencies. The latest version of LuxCore uses 3.9 to be compatible with Blender 3.0. LuxCore has to be built with the same Python version as Blender.

**Comment by neo2068** [comment]
The latest version should work with Blender 3.1 now. [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest)
Please check and comment if it works for you.

**Comment by helsharif** [comment]
Thank you, just tested out now and its working in Blender 3.1 (Windows 11)

**Comment by SteffenDuenner** [comment]
The Python updates that were committed are Windows-only sadly. So no change for Linux users yet.

**Comment by SlincHD** [comment]
thank you @neo2068! it is working now on my pc

**Comment by SteffenDuenner** [comment]
There have been many (futile) attempts to get LuxCore to compile / work with Python 3.10 on Linux during the last few hours it seems...

![image](https://user-images.githubusercontent.com/33224667/159220263-110d38bc-ec78-4459-9720-7aed6ac8e502.png)

**Comment by CodeFHD** [comment]
Closing this issue after a review with the following reasons/conclusions:
- Issue affected old Blender + LuxCore versions that are no longer supported
- Based on answers given, issue is obsolete by now

If you feel this issue is still relevant in 2025, please re-test it with a recent Blender + LuxCore version, then ask to reopen and provide the following information:
- Operating System
- CPU + GPU model
- Blender and LuxCoreRender version used for re-test
- Detailed steps how to reproduce the bug from an empty scene,
- provide a specific .blend-file
