### ISSUE TITLE
LOL: Doesn't show thumbnails

### ISSUE THREAD

**Issue by odil24** [LuxCoreRender/BlendLuxCore#759]
System:
Win10, Blender 3.1 official and LCR v2.61 latest (with LOL assetbar fix)

Problem:
LOL Asset viewer doesn't shows Thumbnail images (just black blanks) but it has saved rendered images on the LOL folder.

**Comment by neo2068** [comment]
Hi! Are there any error messages in the blender console? Is the big image shown when you hover over a thumbnail? In the preview folder there should be a small image version and in the full folder the big image.

**Comment by SlincHD** [comment]
yes i got an eror while trying to use LOL 

Python: Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlendLuxCore\operators\lol\assetbar.py", line 521, in invoke
    ui_bgl.init_ui_size(context, active_area, active_region)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlendLuxCore\draw\lol\viewport.py", line 224, in init_ui_size
    assetbar_props.margin = assetbar_props.bl_rna.properties['margin'].default * ui_scale
TypeError: bpy_struct: item.attr = val: LuxCoreOnlineLibraryAssetBar.margin expected an int type, not float

location: <unknown location>:-1

i hope that helps @neo2068 :D

**Comment by neo2068** [comment]
That error has been fixed in latest build. Please try if it works with that version. [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest)

**Comment by odil24** [comment]
> That error has been fixed in latest build. Please try if it works with that version. [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest)

It doesn't helps. Here another issue when I press to Asset bar button:
```
File "D:\Softwares\Blender\versions\blender-3.1.0-stable(latest)\3.1\scripts\addons\BlendLuxCore\utils\lol\utils.py", line 720, in bg_download_thumbnails
    asset['thumbnail'] = bpy.data.images.load(tpath)
TypeError: unsubscriptable object
```

**Comment by neo2068** [comment]
@odil24 That is a strange error and it should not happen. I cannot reproduce it. Can you test if it gets solved if you push the 'Update ToC from server' button in the addon?

**Comment by odil24** [comment]
> @odil24 That is a strange error and it should not happen. I cannot reproduce it. Can you test if it gets solved if you push the 'Update ToC from server' button in the addon?

![lcr](https://user-images.githubusercontent.com/64298012/160717340-c8e68491-a21d-4497-844f-2d2f3b08a662.jpg)

**Comment by odil24** [comment]
> @odil24 That is a strange error and it should not happen. I cannot reproduce it. Can you test if it gets solved if you push the 'Update ToC from server' button in the addon?

Yes, but it doesn't solved the problem. Something goes wrong I guess.

Thanks for your response.

**Comment by CodeFHD** [comment]
Closing this Issue, which had been left open for some time.
Over the past year, nothing described in this Issue has been reported again, and loading of the images and ToC has just been confirmed by users.

There is a residual problem with a few files, but that is work for a general file-hosting update and not the topic for a BlendLuxCore issue.
