### ISSUE TITLE
Can't activate luxcore

### ISSUE THREAD

**Issue by mahdiaitlmoddan** [LuxCoreRender/BlendLuxCore#760]
Hi,
i ve installed the last version of luxcore in blender 3, when i try to activate it, i get this error:

`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Mahdi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlendLuxCore\__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: DLL load failed while importing pyluxcore: The specified module could not be found.
`
I have already installed the two C++ redistributable

**Comment by neo2068** [comment]
The latest version of BlendLuxCore only is compatible with Blender 3.1. Please use BlendLuxCore v2.6.

**Comment by mahdiaitlmoddan** [comment]
> 

it's installed but when i try to go to render mode, or just to open the node editor, blender juste close without any error message

**Comment by enzyme69** [comment]
Apple M1, Blender LuxCore does not work on Blender 3.1 or any version.

**Comment by epileptrolytics** [comment]
With Apple M1, BlendLuxCore needs Blender 3.1 **Intel**, not ARM version (because Lux is not ported to ARM yet).

**Comment by CodeFHD** [comment]
Closing this issue after a review with the following reasons/conclusions:
- Issue affected old Blender + LuxCore versions that are no longer supported
- Based on answers given, issue is obsolete by now

If you feel this issue is still relevant in 2025, please re-test it with a recent Blender + LuxCore version, then ask to reopen and provide the following information:
- Operating System
- CPU + GPU model
- Blender and LuxCoreRender version used for re-test
- Detailed steps how to reproduce the bug from an empty scene,
- provide a specific .blend-file
