### ISSUE TITLE
Could not import pyluxcore. ImportError

### ISSUE THREAD

**Issue by JapanYoshi** [LuxCoreRender/BlendLuxCore#765]
.blend file:  N/A

Steps to reproduce: Try to install [the latest pre-release](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest) of BlendLuxCore onto Blender 3.0.1

Screenshots or rendered images:
![image](https://user-images.githubusercontent.com/8707990/161748634-5ff9f310-2f8f-4f93-9ec7-78aecac2c263.png)

Error message from Blender console:
```
Modules Installed (BlendLuxCore) from 'C:\\Users\\Haley\\Downloads\\BlendLuxCore-latest-win64.zip' into 'C:\\Users\\Haley\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Haley\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlendLuxCore\__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception:

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: DLL load failed while importing pyluxcore: The specified module could not be found.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Haley\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlendLuxCore\__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception:

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: DLL load failed while importing pyluxcore: The specified module could not be found.
```
All 3 (!) redists are installed.

OS: Windows 10
Blender version: 3.0.1
LuxCore version: latest (I can't find the numerical version number on the page, but Blender says 2.61)

**Comment by odil24** [comment]
Hi. Works fine with Blender 3.3alpha and LuxCoreRender v2.61 (latest) from this:
https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-win64.zip

Install it by copy/paste to "blender_version/scripts/addons/" not by "Install from ZIP".
