### ISSUE TITLE
Problems to activate LuxcoreRender V2.6 win x64

### ISSUE THREAD

**Issue by Klituss** [LuxCoreRender/BlendLuxCore#775]
When I try to enable the LuxcoreRender Addon I get the following error message.

Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\wayne\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlendLuxCore\__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: DLL load failed while importing pyluxcore: Não foi possível encontrar o módulo especificado.

I've installed the microsoft visual C++ 2017 and Intel C++ redistributable.

**Comment by odil24** [comment]
> When I try to enable the LuxcoreRender Addon I get the following error message.
> 
> Traceback (most recent call last): File "D:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable mod = **import**(module_name) File "C:\Users\wayne\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlendLuxCore__init__.py", line 66, in raise Exception(msg + "\n\nImportError: %s" % error) from None Exception:
> 
> Could not import pyluxcore. You probably forgot to install one of the redistributable packages. They are listed in the release announcement post.
> 
> ImportError: DLL load failed while importing pyluxcore: Não foi possível encontrar o módulo especificado.
> 
> I've installed the microsoft visual C++ 2017 and Intel C++ redistributable.

Hi. Works fine with Blender 3.3alpha and LuxCoreRender v2.61 (latest) from this:
https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-win64.zip

Install it by copy/paste to "blender_version/scripts/addons/" not by "Install from ZIP".
