### ISSUE TITLE
Luxcore add-on in blender not working - M1 macbook pro

### ISSUE THREAD

**Issue by agtmn** [LuxCoreRender/BlendLuxCore#777]
Hi everyone, I get an error when i want to enable the  the add-on for luxcore in Blender. it says "could not import pyluxcore". Can anybody help me? Does this have to do something with the M1 core?
![35BC9B28-243D-4C5F-A5BD-5A37C09BC341](https://user-images.githubusercontent.com/106979895/172179536-a7b3aad3-1763-4b50-b871-83603752a132.jpeg)

**Comment by odil24** [comment]
> Hi everyone, I get an error when i want to enable the the add-on for luxcore in Blender. it says "could not import pyluxcore". Can anybody help me? Does this have to do something with the M1 core? ![35BC9B28-243D-4C5F-A5BD-5A37C09BC341](https://user-images.githubusercontent.com/106979895/172179536-a7b3aad3-1763-4b50-b871-83603752a132.jpeg)

Hi. I'm not a MacOS user but maybe this build may have help you?
https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-mac64.zip

Note that, try always extract build to ÿour_blender_version/3.x/scripts/addons" not "Install from ZIP file".

**Comment by JoelGodin** [comment]
I have the same issue, and even when I manually place the unzipped folder into Blender>Contents>Resources>3.2>scripts>addons
it gives the same error. The only difference is now there is no 'Remove' button to remove the addon.

**Comment by JoelGodin** [comment]
I also try Blender 3.3 build from today, and same error.

**Comment by lcombaldieu** [comment]
Same problem here

**Comment by tolozine** [comment]
![11](https://user-images.githubusercontent.com/8479450/202910244-0e9bb416-cfcc-417f-b81b-d954ec4f9a85.png)
same problem again 
apple m1 max
macOS ventura 13.0

**Comment by divan** [comment]
Any solution to this?

**Comment by odil24** [comment]
> Any solution to this?

Hi. Are you tried this?
https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-mac64.zip

**Comment by a-aladawy** [comment]
> > Any solution to this?
> 
> Hi. Are you tried this? https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-mac64.zip

The issue still exists.
I think it's an arm64 support issue.

![Screenshot 2023-01-22 at 10 20 40 AM](https://user-images.githubusercontent.com/12717492/213906762-98128574-dd8b-4cc5-8b4f-d2f4ce3123c0.jpg)

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.4/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/aladawy/Library/Application Support/Blender/3.4/scripts/addons/BlendLuxCore/__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: dlopen(/Users/aladawy/Library/Application Support/Blender/3.4/scripts/addons/BlendLuxCore/bin/pyluxcore.so, 0x0002): tried: '/Users/aladawy/Library/Application Support/Blender/3.4/scripts/addons/BlendLuxCore/bin/pyluxcore.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/aladawy/Library/Application Support/Blender/3.4/scripts/addons/BlendLuxCore/bin/pyluxcore.so' (no such file), '/Users/aladawy/Library/Application Support/Blender/3.4/scripts/addons/BlendLuxCore/bin/pyluxcore.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by polyartin** [comment]
Any update / tips on this? much appreciated!

**Comment by tinashekupfuwa** [comment]
was anyone able to fix this ?

**Comment by alexandersiemert** [comment]
issue still exists, working with MacBook Air M1 and Blender 3.5.1

**Comment by shutupdevon** [comment]
If you use the Intel build of Blender it seems to work, however you lose the performance of Apple Silicon build :(

**Comment by rnln** [comment]
Isn't it because the issue in LuxCore repo about porting to Apple Silicon is still open?
LuxCoreRender/LuxCore#484
Correct me if I'm wrong, but I believe this is a duplicate.
Although the original issue does not contain such detailed information as logs with pyluxcore import errors.

**Comment by JoelGodin** [comment]
I can confirm Luxcorerender v2.6 works with Blender Intel build 2.93.18 LTS with CPU for Film device in settings, on M1 mac.

**Comment by slashv** [comment]
I was successful getting LuxCore 2.6 running on an M1 mac by installing Blender 2.93 LTS x86 which makes it run on through the Rosetta translation layer. To maintain your current version of Blender just drag the application to another location than the Applications folder.

**Comment by lenaschimmel** [comment]
I can also confirm that "Luxcorerender for Blender" v2.8 alpha 1 (a.k.a. BlendLuxCore) works with Blender 4.0.2, as long as you use the Intel build of Blender. 

Not sure why there are two negative reactions to the previous comment - maybe it helps to explain what JoelGodin already implied more explicitly? MacOS can run Intel builds just fine on ARM CPUs, however it can't link x64 libraries to an ARM executable, hence you need to use x64 for both.

The same applies to other LuxCore software (e.g. LuxCore UI 2.6). The only thing that consistently does not work on my M1 CPU is OpenCL support for film, so I have to add `film.opencl.enable = 0` to `render.cfg` to prevent a crash. It seems that BlendLuxCore v2.8 alpha 1 disables that by default, so you don't have to worry about that if you're using a recent version of Blender and BlendLuxCore.

Anyway, I believe that an ARM build of LuxCoreRender would be nice, for multiple reasons:
 - it should result in even better performance
 - Blender users who already use the ARM build of Blender wouldn't need to switch back to x64
 - Apple might end end their support for x86 executables in future versions of MacOS

**Comment by CodeFHD** [comment]
Closing this issue after a review with the following reasons/conclusions:
- (Original) Issue affected old Blender + LuxCore versions that are no longer supported
- Closing this issue to avoid duplicates in the issue list. Any cross-reference in other issues will remain visible
- New build pipeline in preparation inlcudes MacOS ARM build, further issues will need to be tested and handled in that context

If you feel this issue is still relevant in 2025, please re-test it with a recent Blender + LuxCore version, then ask to reopen and provide the following information:
- Operating System
- CPU + GPU model
- Blender and LuxCoreRender version used for re-test
- Detailed steps how to reproduce the bug from an empty scene,
- provide a specific .blend-file
