### ISSUE TITLE
[MacOS Silicon] Could not import pyluxcore

### ISSUE THREAD

**Issue by tinashekupfuwa** [LuxCoreRender/BlendLuxCore#829]
I'm a Mac user, currently using an m2 max, I've been a fan of LuxCore and I just tried adding it to my blender and Im not sure what it has been giving me a hard time.If there's a solution to my issue, please help me.

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/tinashekupfuwa/Library/Application Support/Blender/3.5/scripts/addons/BlendLuxCore/__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: dlopen(/Users/tinashekupfuwa/Library/Application Support/Blender/3.5/scripts/addons/BlendLuxCore/bin/pyluxcore.so, 0x0002): tried: '/Users/tinashekupfuwa/Library/Application Support/Blender/3.5/scripts/addons/BlendLuxCore/bin/pyluxcore.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/tinashekupfuwa/Library/Application Support/Blender/3.5/scripts/addons/BlendLuxCore/bin/pyluxcore.so' (no such file), '/Users/tinashekupfuwa/Library/Application Support/Blender/3.5/scripts/addons/BlendLuxCore/bin/pyluxcore.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by neo2068** [comment]
Hi! Which version of Blendluxcore did you try? This one is for Blender 3.5 and macOS. [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-mac64.zip)

**Comment by Ramirikka** [comment]
Hello @neo2068 i have same issue tried both 3.5 and 2.93LTS versions same error

**Comment by Ramirikka** [comment]
![Screenshot 2023-06-03 at 4 27 19 PM](https://github.com/LuxCoreRender/BlendLuxCore/assets/19676135/f8ddf3a2-60a4-4d54-9854-4ccbe7878fb1)

**Comment by tinashekupfuwa** [comment]
Totally failed.

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/tinashekupfuwa/Library/Application Support/Blender/3.5/scripts/addons/BlendLuxCore/__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: dlopen(/Users/tinashekupfuwa/Library/Application Support/Blender/3.5/scripts/addons/BlendLuxCore/bin/pyluxcore.so, 0x0002): tried: '/Users/tinashekupfuwa/Library/Application Support/Blender/3.5/scripts/addons/BlendLuxCore/bin/pyluxcore.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/tinashekupfuwa/Library/Application Support/Blender/3.5/scripts/addons/BlendLuxCore/bin/pyluxcore.so' (no such file), '/Users/tinashekupfuwa/Library/Application Support/Blender/3.5/scripts/addons/BlendLuxCore/bin/pyluxcore.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by tinashekupfuwa** [comment]
on intel version MacBook Pro,theres no error at all, meaning this problem is being faced by everyone using apple silicon MacBook.

**Comment by Ramirikka** [comment]
Did anyone find a workaround?

**Comment by tinashekupfuwa** [comment]
not yet,I hope the guys working on Luxcore render will hear our cry.

**Comment by tinashekupfuwa** [comment]
Is there any progress towards working on this ?

**Comment by neo2068** [comment]
Hi! As far as I know, nobody is actively working on this. There have been some activities from the mac os maintainer back in 2021 but no news since then.

**Comment by tinashekupfuwa** [comment]
Its a shame, I wish they can continue working with this.This renderer would shine well with Apple Silicon.

**Comment by Perrishnikov** [comment]
Same issue with my Silicon :(

**Comment by MigCurto** [comment]
Its not official, just something I have done for myself (piggybacking @howetuft excellent contribution of making python wheels for pyluxcore) .

But if someone reading this could give a try (I just basically kept everything from luxblendcore alpha1 and stuffed new binaries downloaded from howetuff contribution) - anyone can unzip the file and verify, it probably has extra/redundant files, but works for me:


https://drive.google.com/file/d/1fDprAJxQfreCl3qUnn2ZKepTfz_FCHsX/view?usp=drive_link
Should work on native Blender for Mac ARM 4.2/4.3

https://drive.google.com/file/d/1PDIZb2D392CE7OvyG46_V1xQEJh1Lzsp/view?usp=drive_link
Should work on Blender for Intel 4.2/4.3

**Comment by epileptrolytics** [comment]
Just for information, to make BlendLuxCore work on Apple Silicon, you need to install a Blender-Intel version, not Blender-ARM, because LuxCore was never translated to ARM it is still X86 and needs also Blender-Intel to run (via Rosetta).

**Comment by MigCurto** [comment]
> Just for information, to make BlendLuxCore work on Apple Silicon, you need to install a Blender-Intel version, not Blender-ARM, because LuxCore was never translated to ARM it is still X86 and needs also Blender-Intel to run (via Rosetta).

Not really, have you tried my link? Its not optimized, but works (thanks to @howetuft )

![image](https://github.com/user-attachments/assets/cf02ecd8-9d34-4790-aef8-da80596bce5f)

To be clear, thats Blender for ARM.

**Comment by epileptrolytics** [comment]
> > Just for information, to make BlendLuxCore work on Apple Silicon, you need to install a Blender-Intel version, not Blender-ARM, because LuxCore was never translated to ARM it is still X86 and needs also Blender-Intel to run (via Rosetta).
> 
> Not really, have you tried my link? Its not optimized, but works thanks to @howetuft that found some way (dark magic if you ask me) how to make all dependencies for pyluxcore to instal via pip, so I just did so for Mac ARM , his pyluxcoretest passed (he bundled a test) and copied the respective binaries to BlendLuxCore.
> 
Sorry for confusion, I was replying to the earlier posts years ago suspecting they were trying to install older BlendLuxCore on Blender for ARM.

Now I actually tried your link (ARM), thanks for providing this!
It installs and works out of the box on my MacBook M3 Pro, Sonoma, Blender 4.2.3 ARM.

+ BiDir works 30% faster, also OIDN denoising!
- Path GPU is way slower, the LuxCore2.1 Benchmark scene takes 8min with 460k samples/s compared to 1min with 3.8M samples/s on Blender 3.1 Intel with BlendLuxCore 2.61.

**Comment by MigCurto** [comment]
No worries, thabk you for validating it, it's actually difficult to find other like minded Maci users. AFAIK or understand the general idea is to have BlendLuxCore install from the Blender add ons repo (don't quote me).As it is it's been a confusing few weeks with a lot of changes to the master and not all worked for the best, but @howetuft  work should make it automatic to have all different versions (OSs) at once, also there seems to exist a snag about denoiser being used differently for viewport and render, just the "new" binaries work ok for render but not viewport so I just stuffed the new ones and left old ones as well.

**Comment by howetuft** [comment]
@MigCurto You are utterly right! I just need a few days more...

**Comment by MigCurto** [comment]
>     * BiDir works 30% faster, also OIDN denoising!
> 
> 
>     * Path GPU is way slower, the LuxCore2.1 Benchmark scene takes 8min with 460k samples/s compared to 1min with 3.8M samples/s on Blender 3.1 Intel with BlendLuxCore 2.61.
> 
> 
> Seems OpenCl is not working properly, Activity Monitor shows 100% GPU load though.
> 
> _EDIT:_ After some more experimenting, there are lots of crashes after starting rendering, it is not stable yet.

Hi, could I please bother you to try this one the same way?: 
https://drive.google.com/file/d/1JgEL2fM56tqW4beMP6KITmQqrOalKh0s/view?usp=sharing

I havent done a ton of testing but seems to be working better , and has the latest changes to master BlendLuxCore.
The only weird thing for me is Bidir really seems to be as fast as Path.

**Comment by epileptrolytics** [comment]
> 
> Hi, could I please bother you to try this one the same way?: https://drive.google.com/file/d/1JgEL2fM56tqW4beMP6KITmQqrOalKh0s/view?usp=sharing
> 
> I havent done a ton of testing but seems to be working better , and has the latest changes to master BlendLuxCore. The only weird thing for me is Bidir really seems to be as fast as Path.
> 
Hi, thanks for the update!
This is more stable, apart from a crash when I opened the first scene after installment there were no further crashes.
Behavior is the same with BiDir being faster and PathOCL slower to the point of being unusable.

Still a very promising development!

**Comment by MigCurto** [comment]
@howetuft Did a splendid job, as far as I can see everything seems to be working ok and there's a very noticeable speed difference between using Intel/ARM versions:

https://github.com/LuxCoreRender/BlendLuxCore/actions/runs/12550983375

Would you please be so kind to confirm?
BlendLuxCore-macos_arm64-cp311 

You might need to delete ocl_kernel_cache in your "luxcorerender.org" home folder before trying a new one.

**Comment by epileptrolytics** [comment]
@MigCurto : Thanks for the heads up!
After Blender 4.2 appeared somewhat unstable I have now installed this cp311 bundle on Blender ARM 4.3.2 on MacBook M3 Pro, OS 14.7.2.
Installation worked well, viewport render of the default cube possible with CPU or GPU but GPU is not faster.
I could open different scenes and render in different engines including openCL.

There is a curious bug though: LuxCore render engine opens with halt condition activated and set to 32 samples.
This cannot be changed or deactivated, every render stops after 32 samples, which impedes GPU render testing because it stops too soon.
From this limited testing possibility I could glean that pathGPU now works faster than in the previous ARM builds but not at the speed possible with LuxCore 2.61 with Rosetta/Intel.
In certain scenes I got faster GPU viewport rendering though.

No crashes so far, but one time after the GPU render was finished, CPU went to 100% load and stayed there though no apparent Blender process was active, especially no denoiser, I had to close Blender.

**Comment by odil24** [comment]
@MigCurto @epileptrolytics Fixed "Override halt conditions": 
https://github.com/LuxCoreRender/BlendLuxCore/commit/1528e2ae88220e855d4690245ee5e8d2ceb22a80
