### ISSUE TITLE
 that the class 'LuxCoreRenderEngine' is already registered as a subclass, Help !!!!!

### ISSUE THREAD

**Issue by wizard3376** [LuxCoreRender/BlendLuxCore#872]
I want to enable it, but I get an error

Error message from Blender console:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore\__init__.py", line 84, in register
    engine.register()
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore\engine\__init__.py", line 5, in register
    register_class(base.LuxCoreRenderEngine)
ValueError: register_class(...): already registered as a subclass 'LuxCoreRenderEngine'

OS: Windows 10
Blender version: 4.0.2
LuxCore version: 2.7

**Comment by odil24** [comment]
Hi. Uninstall and reinstall again freshly this build:
https://blenderartists.org/t/luxcorerender-2-7-beta2-for-blender-4-0-only-windows-for-now/1409371?u=odil24

**Comment by pbrt4bounty** [comment]
@odil24  If you distribute binaries that you have not compiled, it would be fair to give credit to whoever created them, don't you think? Cheers..

**Comment by wizard3376** [comment]
Thank you very much!!!
