### ISSUE TITLE
I want to add a texture to a light source in a Luxcore render, but I'm getting an error, HELP!!!!!

### ISSUE THREAD

**Issue by wizard3376** [LuxCoreRender/BlendLuxCore#874]
I want to add a texture to a light source in a Luxcore render, but I get an error

![Снимок экрана (44)](https://github.com/LuxCoreRender/BlendLuxCore/assets/133279496/77433223-946b-4fd7-8933-69287aaa6562)

Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore\operators\texture.py", line 43, in execute
    node_tree = bpy.data.node_groups.new(name=name, type="luxcore_texture_nodes")
TypeError: BlendDataNodeTrees.new(): error with keyword argument "type" -  enum "luxcore_texture_nodes" not found in ('CompositorNodeTree', 'TextureNodeTree', 'luxcore_material_nodes', 'luxcore_volume_nodes', 'GeometryNodeTree', 'ShaderNodeTree')

OS: Windows 10
Blender version: 4.0.2
LuxCore version: 2.7

**Comment by neo2068** [comment]
Hi! I can confirm the issue. The texture node tree is missing for LuxCore. I fixed the issue in the latest commit in for_blender_4 branch. For a projector like effect you could better use a spot light with an image. An area light will add alot of blur unless the emission angle is very low, i.e. < 1°.

**Comment by wizard3376** [comment]
Something like this
![Снимок экрана (48)](https://github.com/LuxCoreRender/BlendLuxCore/assets/133279496/7d5cc21e-257c-410f-acb6-2383c75810cf)

**Comment by wizard3376** [comment]
I'm testing this version of LoxCore, but I'm having the same problems.
https://blenderartists.org/t/luxcorerender-2-7-beta2-for-blender-4-0-only-windows-for-now/1409371?u=odil24

**Comment by neo2068** [comment]
This isn't the latest version, Please use the official repository [here](https://github.com/LuxCoreRender/BlendLuxCore/tree/for_blender_4) or wait until Odil24 updates the download archive.

**Comment by wizard3376** [comment]
I tried to install the new LuxCore from the link

https://github.com/LuxCoreRender/BlendLuxCore/tree/for_blender_4

but got the same error.

Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
mod = importlib.import_module(module_name)
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 1006, in _find_and_load_unlocked
File "", line 688, in _load_unlocked
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-for_blender_4_init.py", line 66, in
raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception:

Maybe I'm doing something wrong? 0<_0?

**Comment by odil24** [comment]
@neo2068 close issue
