### ISSUE TITLE
BlendLuxCore v2.8alpha1 fail to install

### ISSUE THREAD

**Issue by Sharlybg** [LuxCoreRender/BlendLuxCore#883]
Steps to reproduce:
Just trying to install the addon 

Screenshots or rendered images:
none

Error message from Blender console:
`Traceback (most recent call last):
  File "C:\Users\PC\Downloads\blender-4.0.2-windows-x64\blender-4.0.2-windows-x64\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Users\PC\Downloads\blender-4.0.2-windows-x64\blender-4.0.2-windows-x64\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'BlendLuxCore-v2'`

OS: W10 Pro
Blender version: Blender 4.0.2
LuxCore version: BlendLuxCore v2.8alpha1

**Comment by neo2068** [comment]
I cannot reproduce this error. Do you have several addons versions installed? Is there a point in your folder name of the addon?

**Comment by Sharlybg** [comment]
> I cannot reproduce this error. Do you have several addons versions installed? Is there a point in your folder name of the addon?

You are completely on the point folder name was :  "" BlendLuxCore-v2.8alpha1-win64 "" 
Start working when i change it to  :   "" BlendLux281"" 
I have other version.
Thanks you very Much !!!
