### ISSUE TITLE
ERROR: 'Mesh' object has no attribute 'calc_normals_split' / Luxcore 2.8 alpha1,  Blender 4.1 on Tumbleweed

### ISSUE THREAD

**Issue by joc11** [LuxCoreRender/BlendLuxCore#900]
.blend file: 
./.

Steps to reproduce:

Standard Scene. Press F12.

Screenshots or rendered images:

![Screenshot_20240127_214910](https://github.com/LuxCoreRender/BlendLuxCore/assets/39556599/f64eb2af-907e-4ab0-86d6-892864be5f05)

Error message from Blender console:
...
Engine/Final] Rendering layer "View Layer"
[Exporter] Creating session
[SDL][1649.989] Define ImageMap: NamedObject
[SDL][1649.990] Camera type: perspective
[SDL][1649.990] Camera position: Point[7.35889, -6.92579, 4.95831]
[SDL][1649.990] Camera target: Point[6.70733, -6.31162, 4.51304]
[SDL][1649.990] Camera clipping plane disabled
Traceback (most recent call last):
  File "/home/joc/.config/blender/4.1/scripts/addons/BlendLuxCore/engine/base.py", line 91, in render_final
    final.render(self, depsgraph)
  File "/home/joc/.config/blender/4.1/scripts/addons/BlendLuxCore/engine/final.py", line 44, in render
    _render_layer(engine, depsgraph, statistics, layer)
  File "/home/joc/.config/blender/4.1/scripts/addons/BlendLuxCore/engine/final.py", line 56, in _render_layer
    engine.session = engine.exporter.create_session(depsgraph, engine=engine, view_layer=view_layer)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joc/.config/blender/4.1/scripts/addons/BlendLuxCore/export/__init__.py", line 110, in create_session
    instances = self.object_cache2.first_run(self, depsgraph, view_layer, engine, luxcore_scene,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joc/.config/blender/4.1/scripts/addons/BlendLuxCore/export/caches/object_cache.py", line 295, in first_run
    self._convert_obj(exporter, dg_obj_instance, obj, depsgraph, luxcore_scene,
  File "/home/joc/.config/blender/4.1/scripts/addons/BlendLuxCore/export/caches/object_cache.py", line 392, in _convert_obj
    exported_stuff = self._convert_mesh_obj(exporter, dg_obj_instance, obj, obj_key, depsgraph,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joc/.config/blender/4.1/scripts/addons/BlendLuxCore/export/caches/object_cache.py", line 463, in _convert_mesh_obj
    exported_mesh = mesh_converter.convert(obj, mesh_key, depsgraph, luxcore_scene,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joc/.config/blender/4.1/scripts/addons/BlendLuxCore/export/mesh_converter.py", line 42, in convert
    mesh.calc_normals_split()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'calc_normals_split'
ERROR: 'Mesh' object has no attribute 'calc_normals_split'

OS: Tumbleweed
Blender version: 4.1 Alpha
LuxCore version: 2.8 alpha1

**Comment by odil24** [comment]
For now, due to Blender 4.1 API jump up to Python 3.11 version it does not supported Blender 4.1a

**Comment by joc11** [comment]
> For now, due to Blender 4.1 API jump up to Python 3.11 version it does not supported Blender 4.1a

Thank you.
