### ISSUE TITLE
[BlendLuxCore v2.9alpha1] Denoising failed

### ISSUE THREAD

**Issue by foreachthing** [LuxCoreRender/BlendLuxCore#923]
### .blend file: 
Any.

### Steps to reproduce:
Enable viewport denoising (Optix not available, OIDN used), wait for preview to render.
Denoising failed, check console for details.

### Screenshots or rendered images:
![image](https://github.com/LuxCoreRender/BlendLuxCore/assets/10420187/fd6d8191-38f8-46d7-8f15-4f439ccfdefa)

### Error message from Blender console:
<details>
<summary>Console Output</summary>

```
Read prefs: "C:\Users\foreachthing\AppData\Roaming\Blender Foundation\Blender\4.1\config\userpref.blend"
Start generating Sanctus Libraries...
Sanctus Library Size: 442
Loaded SL Previews in 0.16 seconds.
Loading SL Preferences...
BlendLuxCore 2.9alpha1 registered (with pyluxcore 2.9)
Updating device list
Read blend: "C:\Users\foreachthing\Desktop\Blender.blend"
Updating device list
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'GafferHDRIProperties', '', 'hdri'
[SDL][26.344] Define ImageMap: NamedObject
[SDL][26.344] Camera type: perspective
[SDL][26.344] Camera position: Point[0, 0, 0]
[SDL][26.344] Camera target: Point[0, 0, 0]
[SDL][26.344] Camera clipping plane disabled
[LuxCore][26.344] Configuration:
[LuxCore][26.344]   renderengine.type = "RTPATHOCL"
[LuxCore][26.344]   sampler.type = "TILEPATHSAMPLER"
[LuxCore][26.344]   scene.epsilon.min = 1e-05
[LuxCore][26.360]   scene.epsilon.max = 0.1
[LuxCore][26.360]   opencl.devices.select = "10"
[LuxCore][26.360] File Name Resolver Configuration:
==================================================
[Engine/Viewport] New session
[Exporter] Creating session
[SDL][26.422] Define ImageMap: NamedObject
[SDL][26.422] Camera type: perspective
[SDL][26.422] Camera position: Point[7.35889, -6.92579, 3.12435]
[SDL][26.422] Camera target: Point[6.64713, -6.26536, 2.88513]
[SDL][26.422] Camera clipping plane disabled
WARNING: Material "Material": Missing node tree
WARNING: No material defined
[SDL][26.422] Material definition: 2216990102280
[SDL][26.422] Material definition: __CLAY__
[SDL][26.422] Scene objects count: 2
[SDL][26.422] Light definition: __WORLD_BACKGROUND_LIGHT__
[LuxCore][26.438] Configuration:
[LuxCore][26.438]   path.pathdepth.total = 7
[LuxCore][26.438]   path.pathdepth.diffuse = 5
[LuxCore][26.438]   path.pathdepth.glossy = 5
[LuxCore][26.438]   path.pathdepth.specular = 6
[LuxCore][26.438]   path.hybridbackforward.enable = 0
[LuxCore][26.438]   path.hybridbackforward.partition = 0
[LuxCore][26.438]   path.hybridbackforward.glossinessthreshold = 0.049
[LuxCore][26.438]   rtpath.resolutionreduction.preview = 4
[LuxCore][26.438]   rtpath.resolutionreduction.preview.step = 2
[LuxCore][26.438]   rtpath.resolutionreduction = 2
[LuxCore][26.438]   opencl.cpu.use = 0
[LuxCore][26.438]   opencl.gpu.use = 1
[LuxCore][26.438]   opencl.devices.select = "10"
[LuxCore][26.438]   opencl.native.threads.count = 0
[LuxCore][26.453]   renderengine.type = "RTPATHOCL"
[LuxCore][26.453]   sampler.type = "TILEPATHSAMPLER"
[LuxCore][26.453]   film.width = 1586
[LuxCore][26.453]   film.height = 992
[LuxCore][26.453]   film.filter.type = "NONE"
[LuxCore][26.453]   film.filter.width = 1.5
[LuxCore][26.453]   lightstrategy.type = "LOG_POWER"
[LuxCore][26.453]   scene.epsilon.min = 1e-05
[LuxCore][26.453]   scene.epsilon.max = 0.1
[LuxCore][26.453]   path.albedospecular.type = "REFLECT_TRANSMIT"
[LuxCore][26.453]   path.albedospecular.glossinessthreshold = 0.05
[LuxCore][26.453]   film.opencl.enable = 1
[LuxCore][26.453]   film.opencl.device = 0
[LuxCore][26.453]   path.forceblackbackground.enable = 0
[LuxCore][26.453]   renderengine.seed = 1
[LuxCore][26.453]   film.outputs.0.type = "RGB_IMAGEPIPELINE"
[LuxCore][26.453]   film.outputs.0.index = 0
[LuxCore][26.453]   film.outputs.0.filename = "RGB_IMAGEPIPELINE_0.png"
[LuxCore][26.453]   film.outputs.1.type = "ALBEDO"
[LuxCore][26.453]   film.outputs.1.filename = "ALBEDO.exr"
[LuxCore][26.453]   film.outputs.2.type = "AVG_SHADING_NORMAL"
[LuxCore][26.453]   film.outputs.2.filename = "AVG_SHADING_NORMAL.exr"
[LuxCore][26.453]   film.imagepipelines.000.0.type = "NOP"
[LuxCore][26.453]   film.imagepipelines.000.1.type = "TONEMAP_LINEAR"
[LuxCore][26.469]   film.imagepipelines.000.1.scale = 1
[LuxCore][26.469]   film.imagepipelines.000.radiancescales.0.enabled = 1
[LuxCore][26.469]   film.imagepipelines.000.radiancescales.0.globalscale = 1
[LuxCore][26.469]   film.imagepipelines.000.radiancescales.0.rgbscale = 1 1 1
[LuxCore][26.469]   batch.haltspp = 0 0
[LuxCore][26.469]   batch.halttime = 0
[LuxCore][26.469] File Name Resolver Configuration:
Export took 0.0 s
[LuxCore][26.469] Film resolution: 1586x992
[SDL][26.469] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][26.469] Image pipeline: film.imagepipelines.000
[SDL][26.469] Image pipeline step 0: NOP
[SDL][26.469] Image pipeline step 1: TONEMAP_LINEAR
[SDL][26.469] Film output definition: RGB_IMAGEPIPELINE [RGB_IMAGEPIPELINE_0.png]
[SDL][26.469] Film output definition: ALBEDO [ALBEDO.exr]
[SDL][26.469] Film output definition: AVG_SHADING_NORMAL [AVG_SHADING_NORMAL.exr]
[LuxRays][26.469] OpenCL support: enabled
[LuxRays][26.469] OpenCL Platform 0: NVIDIA CUDA
[LuxRays][26.469] CUDA support: enabled
[LuxRays][26.469] CUDA support: available
[LuxRays][26.469] CUDA driver version: 12.40
[LuxRays][26.469] CUDA device count: 1
[LuxRays][26.485] Optix support: available
[LuxRays][26.485] Device 0 name: Native
[LuxRays][26.485] Device 0 type: NATIVE_THREAD
[LuxRays][26.485] Device 0 compute units: 1
[LuxRays][26.485] Device 0 preferred float vector width: 4
[LuxRays][26.485] Device 0 max allocable memory: 17592186044415MBytes
[LuxRays][26.485] Device 0 max allocable memory block size: 17592186044415MBytes
[LuxRays][26.485] Device 0 has out of core memory support: 0
[LuxRays][26.485] Device 1 name: NVIDIA GeForce RTX 2070
[LuxRays][26.485] Device 1 type: OPENCL_GPU
[LuxRays][26.485] Device 1 compute units: 36
[LuxRays][26.485] Device 1 preferred float vector width: 1
[LuxRays][26.485] Device 1 max allocable memory: 8191MBytes
[LuxRays][26.485] Device 1 max allocable memory block size: 2047MBytes
[LuxRays][26.485] Device 1 has out of core memory support: 0
[LuxRays][26.485] Device 2 name: NVIDIA GeForce RTX 2070
[LuxRays][26.485] Device 2 type: CUDA_GPU
[LuxRays][26.485] Device 2 compute units: 64
[LuxRays][26.485] Device 2 preferred float vector width: 1
[LuxRays][26.485] Device 2 max allocable memory: 8191MBytes
[LuxRays][26.485] Device 2 max allocable memory block size: 17592186044415MBytes
[LuxRays][26.485] Device 2 has out of core memory support: 1
[LuxRays][26.485] Device 2 CUDA compute capability: 7.5
[LuxRays][26.485] Creating 1 intersection device(s)
[LuxRays][26.485] Allocating intersection device 0: NVIDIA GeForce RTX 2070 (Type = OPENCL_GPU)
[LuxCore][26.578] CUDA devices used:
[LuxCore][26.578] OpenCL devices used:
[LuxCore][26.578] [NVIDIA GeForce RTX 2070 OpenCLIntersect]
[LuxCore][26.578]   Device OpenCL version: OpenCL 3.0 CUDA
[LuxCore][26.578] Native devices used: 0
[LuxCore][26.578] Configuring 1 OpenCL render threads
[LuxCore][26.578] Configuring 0 native render threads
[LuxRays][26.578] Preprocessing DataSet
[LuxRays][26.578] Total vertex count: 28
[LuxRays][26.578] Total triangle count: 14
[LuxRays][26.578] Preprocessing DataSet done
[LuxRays][26.578] Adding DataSet accelerator: MBVH
[LuxRays][26.578] Total vertex count: 28
[LuxRays][26.578] Total triangle count: 14
[LuxRays][26.578] Building Multilevel Bounding Volume Hierarchy: 2 leafs
[LuxRays][26.578] BVH Dataset preprocessing time: 0ms
[LuxRays][26.578] BVH builder: EMBREE_BINNED_SAH
[LuxRays][26.578] BVH build hierarchy time: 0ms
[LuxRays][26.578] BVH total build time: 0ms
[LuxRays][26.578] Total BVH memory usage: 0Kbytes
[LuxRays][26.578] BVH Dataset preprocessing time: 0ms
[LuxRays][26.578] BVH builder: EMBREE_BINNED_SAH
[LuxRays][26.578] BVH build hierarchy time: 0ms
[LuxRays][26.578] BVH total build time: 0ms
[LuxRays][26.594] Total BVH memory usage: 0Kbytes
[LuxRays][26.594] Building Multilevel Bounding Volume Hierarchy root tree
[LuxRays][26.594] MBVH root tree builder: EMBREE_BINNED_SAH
[LuxRays][26.594] MBVH build time: 16ms
[LuxRays][26.594] Total Multilevel BVH memory usage: 0Kbytes
[LuxRays][26.594] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] MBVH mesh vertices buffer size: 336bytes
[LuxRays][26.594] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] MBVH nodes buffer size: 800bytes
[LuxRays][26.594] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] MBVH leaf transformations buffer size: 128bytes
[LuxRays][26.594] [MBVHKernel] Compiler options: -D LUXRAYS_OPENCL_KERNEL -D PARAM_RAY_EPSILON_MIN=1e-05f -D PARAM_RAY_EPSILON_MAX=0.1f -D LUXRAYS_OPENCL_DEVICE -D LUXRAYS_OS_WINDOWS -cl-fast-relaxed-math -cl-mad-enable
[LuxRays][26.594] [MBVHKernel] Compiling kernels
[LuxRays][26.594] [MBVHKernel] Program cached
[LuxRays][26.594] Adding DataSet accelerator: EMBREE
[LuxRays][26.594] Total vertex count: 28
[LuxRays][26.594] Total triangle count: 14
[LuxRays][26.610] EmbreeAccel build time: 0ms
[LuxCore][26.656] Tiles initialization time: 0.00 secs
[LuxCore][26.656] [PathOCLBaseRenderEngine] OpenCL max. page memory size: 2097072Kbytes
[LuxCore][26.656] Compile Geometry
[LuxCore][26.656] Scene geometry compilation time: 0ms
[LuxCore][26.656] Compile 2 Textures
[LuxCore][26.656] Texture evaluation ops count: 6
[LuxCore][26.672] Texture evaluation max. stack size: 3
[LuxCore][26.672] Textures compilation time: 16ms
[LuxCore][26.672] Compile 2 Materials
[LuxCore][26.672] Material evaluation ops count: 14
[LuxCore][26.672] Material evaluation max. stack size: 8
[LuxCore][26.672] Material compilation time: 0ms
[LuxCore][26.672] Compile Lights
[LuxCore][26.672] Lights compilation time: 0ms
[LuxCore][26.672] Compile ImageMaps
[LuxCore][26.672] Image maps page(s) count: 1
[LuxCore][26.672]  RGB channel page 0 size: 3072Kbytes
[LuxCore][26.672] Image maps compilation time: 0ms
[LuxCore][26.672] Always enabled OpenCL code:
[LuxCore][26.672] Compile Geometry
[LuxCore][26.672] Scene geometry compilation time: 0ms
[LuxCore][26.672] Compile 2 Textures
[LuxCore][26.672] Texture evaluation ops count: 6
[LuxCore][26.672] Texture evaluation max. stack size: 3
[LuxCore][26.672] Textures compilation time: 0ms
[LuxCore][26.672] Compile 2 Materials
[LuxCore][26.672] Material evaluation ops count: 14
[LuxCore][26.672] Material evaluation max. stack size: 8
[LuxCore][26.672] Material compilation time: 0ms
[LuxCore][26.672] Compile Lights
[LuxCore][26.672] Lights compilation time: 0ms
[LuxCore][26.672] Compile ImageMaps
[LuxCore][26.672] Image maps page(s) count: 1
[LuxCore][26.672]  RGB channel page 0 size: 3072Kbytes
[LuxCore][26.672] Image maps compilation time: 0ms
[LuxCore][26.672] Starting 1 OpenCL render threads
[LuxRays][26.688] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] RADIANCE_PER_PIXEL_NORMALIZEDs[0] buffer size: 24,614Kbytes
[LuxRays][26.688] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] ALBEDO buffer size: 24,614Kbytes
[LuxRays][26.703] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] AVG_SHADING_NORMAL buffer size: 24,614Kbytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] RADIANCE_PER_PIXEL_NORMALIZEDs[0] buffer size: 24,614Kbytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Camera buffer size: 5,492bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Normals buffer size: 336bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] UVs buffer size: 224bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Triangle normals buffer size: 168bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Vertices buffer size: 336bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Triangles buffer size: 168bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Mesh description buffer size: 624bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] ImageMap descriptions buffer size: 40bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] ImageMaps buffer size: 3,072Kbytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Textures buffer size: 656bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Texture evaluation ops buffer size: 48bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Texture evaluation stacks buffer size: 4,704Kbytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Materials buffer size: 456bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Material evaluation ops buffer size: 168bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Material evaluation stacks buffer size: 12,544Kbytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Scene objects buffer size: 48bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Lights buffer size: 344bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Env. light indices buffer size: 4bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Light offsets (Part I) buffer size: 8bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Env. light distributions buffer size: 1,028Kbytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] LightsDistribution buffer size: 16bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] InfiniteLightSourcesDistribution buffer size: 16bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Ray buffer size: 18,816Kbytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] RayHit buffer size: 7,840Kbytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] GPUTaskConfiguration buffer size: 336bytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] GPUTask buffer size: 260,288Kbytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] GPUTaskDirectLight buffer size: 23,520Kbytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] GPUTaskState buffer size: 153,664Kbytes
[LuxRays][26.719] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] GPUTask Stats buffer size: 1,568Kbytes
[LuxRays][26.735] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] SamplerSharedData buffer size: 36bytes
[LuxCore][26.735] [PathOCLBaseRenderThread::0] Size of a Sample: 16bytes
[LuxRays][26.735] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Sample buffer size: 6,272Kbytes
[LuxCore][26.735] [PathOCLBaseRenderThread::0] Size of a SampleData: 8bytes
[LuxRays][26.735] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] SampleData buffer size: 3,136Kbytes
[LuxCore][26.735] [PathOCLBaseRenderThread::0] Size of a SampleResult: 428bytes
[LuxRays][26.735] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] SampleResult buffer size: 167,776Kbytes
[LuxRays][26.735] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] PathInfo buffer size: 42,336Kbytes
[LuxRays][26.735] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] DirectLightVolumeInfo buffer size: 17,248Kbytes
[LuxRays][26.735] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Pixel Filter Distribution buffer size: 33Kbytes
[LuxCore][26.735] [PathOCLBaseRenderThread::0] Compiling kernels
[LuxRays][26.735] [PathOCL kernel] Compiler options: -D LUXRAYS_OPENCL_KERNEL -D SLG_OPENCL_KERNEL -D RENDER_ENGINE_RTPATHOCL -D PARAM_RAY_EPSILON_MIN=1e-05f -D PARAM_RAY_EPSILON_MAX=0.1f -D LUXCORE_NVIDIA_OPENCL -D LUXRAYS_OPENCL_DEVICE -D LUXRAYS_OS_WINDOWS -cl-fast-relaxed-math -cl-mad-enable
[LuxRays][26.735] [PathOCL kernel] Compiling kernels
[LuxRays][26.781] [PathOCL kernel] Program cached
[LuxCore][26.781] [PathOCLBaseRenderThread::0] Compiling Film_Clear Kernel
[LuxCore][26.781] [PathOCLBaseRenderThread::0] Compiling InitSeed Kernel
[LuxCore][26.781] [PathOCLBaseRenderThread::0] Compiling Init Kernel
[LuxCore][26.781] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_RT_NEXT_VERTEX Kernel
[LuxCore][26.781] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_HIT_NOTHING Kernel
[LuxCore][26.781] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_HIT_OBJECT Kernel
[LuxCore][26.781] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_RT_DL Kernel
[LuxCore][26.781] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_DL_ILLUMINATE Kernel
[LuxCore][26.781] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_DL_SAMPLE_BSDF Kernel
[LuxCore][26.781] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_GENERATE_NEXT_VERTEX_RAY Kernel
[LuxCore][26.797] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_SPLAT_SAMPLE Kernel
[LuxCore][26.797] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_NEXT_SAMPLE Kernel
[LuxCore][26.797] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_GENERATE_CAMERA_RAY Kernel
[LuxCore][26.797] [PathOCLBaseRenderThread::0] AdvancePaths_MK_* workgroup size: 32
[LuxCore][26.797] [PathOCLBaseRenderThread::0] Kernels compilation time: 61ms
[LuxCore][26.797] Starting 0 native render threads
[LuxCore][26.813] Film hardware image pipeline
[LuxCore][26.875] Film hardware device used: NVIDIA GeForce RTX 2070 OpenCLIntersect (Type: OPENCL_GPU)
[LuxCore][26.875]   Device OpenCL version: OpenCL 3.0 CUDA
[LuxRays][26.875] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] IMAGEPIPELINE buffer size: 18,437Kbytes
[LuxRays][26.891] [Device NVIDIA GeForce RTX 2070 OpenCLIntersect] Merge buffer size: 24,583Kbytes
[LuxRays][26.891] [MergeSampleBuffersOCL] Compiler options: -D LUXRAYS_OPENCL_KERNEL -D SLG_OPENCL_KERNEL -D LUXRAYS_OPENCL_DEVICE -D LUXRAYS_OS_WINDOWS -cl-fast-relaxed-math -cl-mad-enable
[LuxRays][26.891] [MergeSampleBuffersOCL] Compiling kernels
[LuxRays][26.891] [MergeSampleBuffersOCL] Program cached
[LuxCore][26.891] [MergeSampleBuffersOCL] Compiling Film_MergeBufferInitialize Kernel
[LuxCore][26.891] [MergeSampleBuffersOCL] Compiling Film_MergeRADIANCE_PER_PIXEL_NORMALIZED Kernel
[LuxCore][26.891] [MergeSampleBuffersOCL] Compiling Film_MergeRADIANCE_PER_SCREEN_NORMALIZED Kernel
[LuxCore][26.891] [MergeSampleBuffersOCL] Compiling Film_MergeBufferFinalize Kernel
[LuxCore][26.891] [MergeSampleBuffersOCL] Kernels compilation time: 0ms
[LuxRays][26.906] [LinearToneMap] Compiler options: -D LUXRAYS_OPENCL_KERNEL -D SLG_OPENCL_KERNEL -D LUXRAYS_OPENCL_DEVICE -D LUXRAYS_OS_WINDOWS -cl-fast-relaxed-math -cl-mad-enable
[LuxRays][26.906] [LinearToneMap] Compiling kernels
[LuxRays][26.906] [LinearToneMap] Program cached
[LuxCore][26.906] [AutoLinearToneMap] Compiling LinearToneMap_Apply Kernel
[LuxCore][26.906] [LinearToneMap] Kernels compilation time: 0ms
[Engine/Viewport] Pausing session
[LuxCore][29.016] [NVIDIA GeForce RTX 2070 OpenCLIntersect] Memory used for hardware image pipeline: 43020Kbytes
Traceback (most recent call last):
  File "C:\Users\foreachthing\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlendLuxCore\draw\viewport.py", line 173, in load_denoiser_result
    with open(self._denoised_file_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\foreachthing\\AppData\\Local\\Temp\\2216707172432_denoised.pfm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\foreachthing\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlendLuxCore\engine\base.py", line 128, in view_draw
    viewport.view_draw(self, context, depsgraph)
  File "C:\Users\foreachthing\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlendLuxCore\engine\viewport.py", line 221, in view_draw
    framebuffer.load_denoiser_result(scene)
  File "C:\Users\foreachthing\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlendLuxCore\draw\viewport.py", line 178, in load_denoiser_result
    raise Exception("Denoising failed, check console for details")
Exception: Denoising failed, check console for details
```
</details>

OS: Windows 11
Blender version: 4.11
LuxCore version: 2.9a1

**Comment by neo2068** [comment]
Hi, this is a known error. For viewport render only OPTIX denoiser works.

**Comment by foreachthing** [comment]
Ok. But Optix is not available with BlendLuxCore?!
I can use Optix with Cycles, though.

**Comment by neo2068** [comment]
Hi! For OPTIX usage, you need to set a CUDA film device in the addon preferences. 
![grafik](https://github.com/LuxCoreRender/BlendLuxCore/assets/17701407/7ab40589-55d9-45db-a40d-de4e991f94fd)

**Comment by neo2068** [comment]
I pushed a new version of the addon. Please download the new archive. There were misssing dlls for the viewport oidn denoiser. Now, it should work with OIDN, too.

**Comment by foreachthing** [comment]
Works with OIDN and Optix! 🙏🏼

**Comment by odil24** [comment]
@neo2068 Hi. In my case OptiX does not working only OIDN works

Specs:
GTX 1060 6GB (Nvidia driver: v555.85)

Info:
It does works before (but my previous driver is v530, it does mean maybe?)

![1172](https://github.com/LuxCoreRender/BlendLuxCore/assets/64298012/fa7f701b-486c-4353-854b-17a0ee1ba0d9)
