### ISSUE TITLE
LoL don't run with Blender 4.1.1 and BlendLuxCore v2.9

### ISSUE THREAD

**Issue by Spirou4D** [LuxCoreRender/BlendLuxCore#930]
.blend file: 
A simple cube on 3Dview

Steps to reproduce:
Install BlendLuxCore 2.9 for Blender 4.1 and LoL in HOME/LuxCoreOnlineLibrary_data

Screenshots or rendered images:

Error message from Blender console:
Python: Traceback (most recent call last):
  File "D:\Users\Patrick\Mes Applications\blender-4.1.1\4.1\python\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\Users\Patrick\Mes Applications\blender-4.1.1\4.1\python\Lib\http\client.py", line 1294, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Users\Patrick\Mes Applications\blender-4.1.1\4.1\python\Lib\http\client.py", line 1340, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Users\Patrick\Mes Applications\blender-4.1.1\4.1\python\Lib\http\client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Users\Patrick\Mes Applications\blender-4.1.1\4.1\python\Lib\http\client.py", line 1048, in _send_output
    self.send(msg)
  File "D:\Users\Patrick\Mes Applications\blender-4.1.1\4.1\python\Lib\http\client.py", line 986, in send
    self.connect()
  File "D:\Users\Patrick\Mes Applications\blender-4.1.1\4.1\python\Lib\http\client.py", line 1466, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Patrick\Mes Applications\blender-4.1.1\4.1\python\Lib\ssl.py", line 517, in wrap_sockets
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Patrick\Mes Applications\blender-4.1.1\4.1\python\Lib\ssl.py", line 1108, in _create
    self.do_handshake()
  File "D:\Users\Patrick\Mes Applications\blender-4.1.1\4.1\python\Lib\ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Patrick\Mes Applications\blender-4.1.1\4.1\python\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)>

OS: Windows 10 updated.
Blender version: 4.1.1 win54bites
LuxCore version: v2.9

**Comment by Spirou4D** [comment]
Here is the solution: the LuxCoreRender's URL : https://luxcorerender.org/download/lol  can't be connected because the sercurity certificat is expired !!!

Nom commun (CN)	www.luxcorerender.org
Organisation (O)	<Ne fait pas partie du certificat>
Unité d'organisation (OU)	<Ne fait pas partie du certificat>
Nom commun (CN)	Sectigo RSA Domain Validation Secure Server CA
Organisation (O)	Sectigo Limited
Unité d'organisation (OU)	<Ne fait pas partie du certificat>
Émis le	lundi 26 juin 2023 à 02:00:00
Expire le	jeudi 4 juillet 2024 à 01:59:59
Certificat	3be1fe7e9217328b02b7d3076f1aa6b9b6e6594740acbe83f2065852c36b1d65
Clé publique	8559643ca2b3dd859f353899a4715ca5cac505b2033464662ba0fdb84b53e5ac

**Comment by Sarah-C** [comment]
It's also 404 (NOT FOUND) on http!

Have they removed the textures?  Oh no! That means..........

**Comment by odil24** [comment]
Here fixed:
https://github.com/LuxCoreRender/BlendLuxCore/pull/934/commits/9195c15fde8ce25e22fa2ffddcdeaabcb4611c6b
