### ISSUE TITLE
Imagepipeline: 'LuxCoreImagepipeline' object has no attribute 'denoiser'

### ISSUE THREAD

**Issue by alnjmalsaat3** [LuxCoreRender/BlendLuxCore#942]
Steps to reproduce:

When I use the OptiX denoiser in viewport render.

Intel Open Image Denoiser work fine without problems.

Screenshots or rendered images:
![image](https://github.com/user-attachments/assets/c9e3a7de-752d-4867-a0ac-78cf9f2f19d3)

Error message from Error Log:
Imagepipeline: 'LuxCoreImagepipeline' object has no attribute 'denoiser'

Error message from Blender console:
Traceback (most recent call last):
  File "C:\Users\alnjm\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\BlendLuxCore\export\imagepipeline.py", line 30, in convert
    convert_defs(context, scene, definitions, 0)
  File "C:\Users\alnjm\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\BlendLuxCore\export\imagepipeline.py", line 59, in convert_defs
    results.append(pool.apply_async(_denoise_effect, (definitions, index, pipeline.denoiser)))
                                                                          ^^^^^^^^^^^^^^^^^
AttributeError: 'LuxCoreImagepipeline' object has no attribute 'denoiser'
WARNING: Imagepipeline: 'LuxCoreImagepipeline' object has no attribute 'denoiser'
[Engine] del: RenderEngine struct was already deleted
[LuxRays][3135.984] [Optix][4][DISKCACHE] Closed database: "C:\Users\alnjm\AppData\Local\NVIDIA\OptixCache\optix7cache.db"
[LuxRays][3135.984] [Optix][4][DISKCACHE]     Cache data size: "120.9 MiB"
[LuxCore][3136.000] [NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Memory used for hardware image pipeline: 58988Kbytes
Traceback (most recent call last):
  File "C:\Users\alnjm\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\BlendLuxCore\engine\base.py", line 124, in view_update
    viewport.view_update(self, context, depsgraph)
  File "C:\Users\alnjm\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\BlendLuxCore\engine\viewport.py", line 153, in view_update
    force_session_restart(engine)
    ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'force_session_restart' is not defined

OS: win 11 rtx 4060 ti
Blender version: 4.3
LuxCore version:  2.9 beta 2

**Comment by odil24** [comment]
An issue has fixed. Thanks.
